import type { ItemDef } from "./types";

export const itemsCars2: ItemDef[] = [
  // --- cars_paradox_of_choice (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_paradox_of_choice",
    stem: "According to the passage, the traditional assumption that more options make a decision-maker better off treats the act of choosing as:",
    reasoning: "The passage states this assumption 'treats the act of choosing itself as costless,' which the passage then goes on to challenge.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Costless", correct: true },
      { text: "Extremely expensive in terms of time", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage attributes this 'costly' view to its own counterargument, not to the traditional assumption being described here." },
      { text: "Impossible without expert guidance", errorType: "outside_knowledge_not_supported_by_passage", why: "Expert guidance is never mentioned in the passage." },
      { text: "Something only wealthy individuals can afford to do carefully", errorType: "outside_knowledge_not_supported_by_passage", why: "Wealth is not a factor discussed anywhere in the passage." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_paradox_of_choice",
    stem: "The passage argues that beyond some point, additional alternatives can leave a chooser:",
    reasoning: "The passage states additional alternatives can leave a chooser 'not better equipped but more anxious about having overlooked a superior option, and more prone to regret.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "More anxious and more prone to regret, not better equipped", correct: true },
      { text: "Completely unable to make any decision at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes increased anxiety and regret, not a total inability to decide." },
      { text: "Better equipped to make the objectively correct choice", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly says the chooser is 'not better equipped,' the opposite of this claim." },
      { text: "Indifferent to the outcome of the decision", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes heightened anxiety and regret, not indifference." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_paradox_of_choice",
    stem: "The passage's claim that the traditional economic picture of choice 'understates a real cost' depends most directly on treating which of the following as a genuine cost?",
    reasoning: "The passage's central move is treating the time, attention, and confidence spent evaluating additional options as a real cost of choosing itself — this is the 'real cost that scales with the size of the option set' the passage refers to.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "The time, attention, and confidence spent evaluating each additional option", correct: true },
      { text: "The monetary price difference between the cheapest and most expensive option", errorType: "outside_knowledge_not_supported_by_passage", why: "Price differences between options are never discussed in the passage; the cost concerns evaluation effort, not price." },
      { text: "The cost of returning an item after purchase", errorType: "outside_knowledge_not_supported_by_passage", why: "Post-purchase returns are not discussed anywhere in the passage." },
      { text: "The cost of advertising each additional option to consumers", errorType: "outside_knowledge_not_supported_by_passage", why: "Advertising costs are not part of the passage's argument, which focuses on the chooser's own evaluation costs." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_paradox_of_choice",
    stem: "Which finding would most directly support the passage's argument?",
    reasoning: "The passage's core claim is that more options can decrease, not increase, satisfaction once evaluation costs are accounted for; a finding that shoppers given fewer choices report greater satisfaction and confidence would directly support this.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Shoppers offered a smaller selection of jams report higher satisfaction with their purchase than those offered a much larger selection", correct: true },
      { text: "Shoppers offered a larger selection of jams spend more money overall", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "Spending more money doesn't address the passage's specific claim about anxiety, regret, and satisfaction from excess choice." },
      { text: "Shoppers prefer stores with brightly colored packaging", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Packaging color is irrelevant to the passage's argument about the cost of evaluating many alternatives." },
      { text: "Shoppers take the same amount of time regardless of how many options are offered", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "If evaluation time didn't scale with options, this would actually undercut, not support, the passage's argument about cognitive costs scaling with option set size." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_paradox_of_choice",
    stem: "According to the passage, additional alternatives can be 'ignored, never mandatory.' This point is raised in order to:",
    reasoning: "The passage raises this point to state the traditional assumption fairly before challenging it — acknowledging that, superficially, more options seem harmless since none must be chosen, before arguing this overlooks the real cost of evaluation.",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "State the traditional justification for why more options seem harmless, before challenging it", correct: true },
      { text: "Prove conclusively that more options are always beneficial", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage goes on to challenge, not affirm, the idea that more options are simply beneficial." },
      { text: "Argue that people frequently choose options at random", errorType: "outside_knowledge_not_supported_by_passage", why: "Random choice is not something the passage discusses." },
      { text: "Suggest that ignoring most options is itself costly", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's argument is that evaluating (not simply ignoring) options carries a cost; ignoring an option is exactly what the traditional view says is costless." },
    ],
  },

  // --- cars_built_environment (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_built_environment",
    stem: "According to the passage, traffic engineers have traditionally treated pedestrian and cyclist safety as:",
    reasoning: "The passage states engineers have treated safety 'as a constraint to be satisfied rather than a design goal in its own right.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "A constraint to be satisfied, not a primary design goal", correct: true },
      { text: "The single most important design priority", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly contrasts this with efficient vehicle movement being the primary traditional priority." },
      { text: "Entirely irrelevant to street design", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes safety as a constraint that must be satisfied, not something ignored entirely." },
      { text: "A legal requirement enforced only in urban areas", errorType: "outside_knowledge_not_supported_by_passage", why: "Legal requirements and urban/rural distinctions are not discussed in the passage." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_built_environment",
    stem: "The passage argues that street design influences driver behavior more than:",
    reasoning: "The passage explicitly states street design does more to determine driver behavior 'than posted speed limits or signage ever could.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Posted speed limits or signage", correct: true },
      { text: "The driver's personal driving history", errorType: "outside_knowledge_not_supported_by_passage", why: "Driving history is never discussed in the passage as a comparison point." },
      { text: "Weather conditions", errorType: "outside_knowledge_not_supported_by_passage", why: "Weather is not mentioned anywhere in the passage." },
      { text: "The type of vehicle being driven", errorType: "outside_knowledge_not_supported_by_passage", why: "Vehicle type is not a comparison the passage makes." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_built_environment",
    stem: "According to the passage, a narrower street with parked cars and tighter turns slows traffic because it:",
    reasoning: "The passage states such features make 'higher speeds feel effortful and risky to the driver' — a psychological/perceptual mechanism, not a physical barrier preventing speed.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Makes higher speeds feel effortful and risky to the driver", correct: true },
      { text: "Physically prevents cars from exceeding a certain speed", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes a perceptual/behavioral effect on the driver, not a physical mechanical restriction on the vehicle." },
      { text: "Triggers an automatic speed limiter installed in most cars", errorType: "outside_knowledge_not_supported_by_passage", why: "No such technology is discussed in the passage; the mechanism described is psychological, related to driver perception." },
      { text: "Requires police enforcement to be effective", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage explicitly frames this as an alternative to relying on enforcement, not a mechanism requiring it." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_built_environment",
    stem: "Based on the passage's argument, which intervention would most likely be predicted to reduce speeding on a dangerous street?",
    reasoning: "Consistent with the passage's argument that design (not signage or enforcement) shapes driver behavior, narrowing the street or adding visual obstructions would be predicted to reduce speeding more effectively than simply changing signage.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Narrowing the street and adding visual obstructions like trees or parked cars", correct: true },
      { text: "Posting a lower speed limit sign without changing the street itself", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage explicitly argues signage alone does less to shape behavior than the street's physical design." },
      { text: "Increasing the fine for speeding tickets", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's argument centers on design, not enforcement penalties, as the more effective lever." },
      { text: "Adding more streetlights along the road", errorType: "outside_knowledge_not_supported_by_passage", why: "Lighting is not discussed in the passage as a factor influencing driver speed behavior." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_built_environment",
    stem: "According to the passage, a persistent speeding problem on a given street should be understood as evidence that:",
    reasoning: "The passage's closing claim is that persistent speeding is 'evidence that the street itself was designed for a different, faster kind of use than the one now considered desirable.'",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "The street was designed for a faster kind of use than is now desired", correct: true },
      { text: "Drivers in that area are unusually reckless as individuals", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames the problem as a design issue, not primarily an issue of individual driver character." },
      { text: "Speed limit enforcement in the area needs to be doubled", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's proposed alternative is treating this as a design issue, not primarily calling for more enforcement." },
      { text: "The street has not been resurfaced recently enough", errorType: "outside_knowledge_not_supported_by_passage", why: "Road surface maintenance is never discussed in the passage." },
    ],
  },

  // --- cars_humor_theory (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_humor_theory",
    stem: "According to the passage, theories of humor have struggled to explain why incongruity is:",
    reasoning: "The passage states theories have struggled to explain why incongruity 'is sometimes funny and sometimes merely confusing or unsettling.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Sometimes funny and sometimes merely confusing or unsettling", correct: true },
      { text: "Always perceived identically by every listener", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's puzzle is precisely that reactions to incongruity vary, not that they're always identical." },
      { text: "Never actually present in genuinely funny jokes", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage treats incongruity as central to humor, not absent from it." },
      { text: "Only found in jokes told by professional comedians", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage makes no claim restricting incongruity to professional comedy." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_humor_theory",
    stem: "The passage's proposed answer holds that an incongruous violation must be resolved as:",
    reasoning: "The passage states the violation 'must also be resolved as benign, understood by the listener as ultimately safe, harmless, or not a real threat.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Benign, safe, or harmless once its logic is worked out", correct: true },
      { text: "Completely illogical, with no resolution possible", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's account requires the violation to be resolved, not to remain permanently illogical." },
      { text: "Genuinely threatening to the listener's safety", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's theory says a benign, not threatening, resolution is what makes something land as comedy." },
      { text: "Identical to a previously heard joke", errorType: "outside_knowledge_not_supported_by_passage", why: "Similarity to prior jokes is not part of the theory the passage describes." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_humor_theory",
    stem: "The passage explains that identical incongruous premises can land as either comedy or horror depending on:",
    reasoning: "The passage attributes this difference to 'whether the surrounding context signals safety or danger' — the same core incongruity, differently contextualized.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Whether the surrounding context signals safety or danger", correct: true },
      { text: "The specific wording used to phrase the joke", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage attributes the difference to contextual signaling of safety versus danger, not to specific wording choices." },
      { text: "How many people are present to hear the joke", errorType: "outside_knowledge_not_supported_by_passage", why: "Audience size is not discussed in the passage as the relevant factor." },
      { text: "Whether the joke is delivered in written or spoken form", errorType: "outside_knowledge_not_supported_by_passage", why: "Medium of delivery is not the factor the passage identifies for this difference." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_humor_theory",
    stem: "Which observation would most directly support the passage's proposed theory of humor?",
    reasoning: "The theory predicts that the same incongruous content should be perceived as funny or unsettling depending on contextual safety cues; direct evidence of exactly this — identical content shifting from funny to disturbing based on framing — would support the theory.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "The same joke about a mishap is rated as funny when framed as fictional, but disturbing when the audience believes it really happened to someone badly hurt", correct: true },
      { text: "Different audiences rate the same joke with similar average funniness scores", errorType: "true_statement_that_does_not_answer_the_question", why: "Consistent ratings across audiences doesn't test the specific safety-versus-danger framing mechanism the passage proposes." },
      { text: "Comedians report that writing jokes requires years of practice", errorType: "true_statement_that_does_not_answer_the_question", why: "This speaks to skill development, not to the specific mechanism of benign-violation resolution the passage proposes." },
      { text: "Jokes translated into other languages are rated as equally funny", errorType: "true_statement_that_does_not_answer_the_question", why: "Cross-language translation success doesn't test the safety/danger contextual framing mechanism specifically." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_humor_theory",
    stem: "According to the passage, one influential answer to the humor puzzle holds that incongruity alone is:",
    reasoning: "The passage states 'incongruity alone is not sufficient' — a violation must also be resolved as benign for it to be perceived as funny.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Not sufficient by itself to produce humor", correct: true },
      { text: "The only ingredient required for something to be funny", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states incongruity alone is not sufficient, contradicting this claim." },
      { text: "Entirely unrelated to whether something is perceived as funny", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage treats incongruity as a necessary, just not sufficient, component of humor." },
      { text: "Something only children find amusing", errorType: "outside_knowledge_not_supported_by_passage", why: "Age-related differences in humor perception are not discussed in the passage." },
    ],
  },

  // --- cars_ship_of_theseus (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_ship_of_theseus",
    stem: "According to the passage, most people's initial intuition is that a ship with gradually replaced planks:",
    reasoning: "The passage states 'most people's intuitions say yes — gradual replacement seems compatible with persistence of identity.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Remains the same ship", correct: true },
      { text: "Immediately becomes a completely different ship after the first plank is replaced", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the intuition as supporting continued identity through gradual replacement, not an immediate change after one plank." },
      { text: "Was never really a single, unified ship to begin with", errorType: "outside_knowledge_not_supported_by_passage", why: "Not a claim the passage makes about the initial intuition." },
      { text: "Cannot be judged using ordinary intuitions at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly describes what most people's intuitions say about this first scenario." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_ship_of_theseus",
    stem: "The passage's twist involving the reassembled second ship is introduced primarily to:",
    reasoning: "The twist is introduced to show that the initial intuition (gradual replacement preserves identity) breaks down once a genuine rival candidate for 'the real ship' exists — revealing the limits of that intuition.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Show that the initial intuition about gradual replacement breaks down under a further test", correct: true },
      { text: "Prove definitively that the original ship was destroyed the moment repairs began", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage doesn't conclude the original ship was destroyed; it raises a puzzle about which ship (if either) is the 'real' one." },
      { text: "Demonstrate that reassembling discarded planks is physically impossible", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't question the physical possibility of reassembly; it uses the scenario to test criteria of identity." },
      { text: "Argue that ships, unlike other objects, have no persistent identity at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage generalizes beyond ships to identity criteria broadly, not a claim specific to ships lacking identity." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_ship_of_theseus",
    stem: "According to the passage, the two-ship scenario shows there is 'no principled way' to award the title of 'real' ship to one candidate over the other, using:",
    reasoning: "The passage specifies this is true 'using only the criteria that made the first scenario feel unproblematic' — i.e., the same intuitive criteria that worked fine for the simple gradual-replacement case fail to adjudicate between the two candidates.",
    difficulty: 0.5,
    sirs: 2,
    options: [
      { text: "The same criteria that made the original single-ship scenario feel unproblematic", correct: true },
      { text: "Any criteria whatsoever, even ones never previously considered", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage specifically limits this claim to the original criteria, not to every conceivable criterion." },
      { text: "A vote among the ship's original crew members", errorType: "outside_knowledge_not_supported_by_passage", why: "Crew voting is not a mechanism the passage discusses." },
      { text: "The physical size of each candidate ship", errorType: "outside_knowledge_not_supported_by_passage", why: "Ship size is not a criterion the passage raises in this discussion." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_ship_of_theseus",
    stem: "The passage's conclusion, that ordinary identity criteria 'quietly diverge once pushed to their limits,' is best illustrated by which additional example?",
    reasoning: "A case where two distinct, ordinarily-aligned criteria for identity (such as psychological continuity and physical/bodily continuity) point to different answers when pulled apart — like a hypothetical mind transferred to a new body — parallels the ship puzzle's structure of criteria that normally agree but diverge under an extreme test.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "A thought experiment where a person's memories and personality are transferred to an entirely new body, leaving open whether the original person now exists in the old or new body", correct: true },
      { text: "A car that receives a routine oil change and tire rotation", errorType: "outside_knowledge_not_supported_by_passage", why: "Routine maintenance doesn't create any tension between different criteria of identity, unlike the ship puzzle's structure." },
      { text: "A company that changes its logo but keeps the same employees and headquarters", errorType: "outside_knowledge_not_supported_by_passage", why: "This scenario doesn't pit competing identity criteria against each other in the way the ship puzzle does." },
      { text: "A recipe that is followed exactly the same way every time it is cooked", errorType: "outside_knowledge_not_supported_by_passage", why: "No identity puzzle or divergence of criteria arises from repeating an identical process." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_ship_of_theseus",
    stem: "According to the passage, the ancient puzzle originally concerns a ship whose planks are replaced:",
    reasoning: "The passage states the planks are replaced 'one at a time, during routine repairs' — a gradual process, not all at once.",
    difficulty: 0.1,
    sirs: 1,
    options: [
      { text: "One at a time, during routine repairs", correct: true },
      { text: "All at once, in a single dramatic event", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly describes gradual, one-at-a-time replacement, not a single simultaneous event." },
      { text: "Only after the ship has completely sunk", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage describes ongoing routine repairs to a functioning ship, not repairs after sinking." },
      { text: "By a different crew than the ship's original builders", errorType: "outside_knowledge_not_supported_by_passage", why: "Who performs the repairs is never specified or relevant in the passage." },
    ],
  },

  // --- cars_anthropomorphism (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_anthropomorphism",
    stem: "According to the passage, one explanation for polite behavior toward chatbots dismisses it as:",
    reasoning: "The passage states one explanation 'dismisses this as simple confusion, a failure to fully internalize that no one is home behind the interface.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Simple confusion about what the chatbot actually is", correct: true },
      { text: "A deliberate, sophisticated philosophical stance", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes this explanation as dismissing the behavior as a mistake, not treating it as sophisticated or deliberate." },
      { text: "Proof that chatbots are in fact conscious", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states users 'know it is not conscious,' so this explanation doesn't claim chatbots are conscious." },
      { text: "A behavior found only among children", errorType: "outside_knowledge_not_supported_by_passage", why: "Age is not discussed anywhere in the passage." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_anthropomorphism",
    stem: "The passage's 'more interesting explanation' reframes politeness toward a chatbot as being fundamentally about:",
    reasoning: "The passage states this explanation holds the politeness 'is not really about the machine at all: it is a form of self-regulation' — about maintaining the user's own habits of civility.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "The user's own self-regulation and maintenance of civil habits", correct: true },
      { text: "The chatbot's programmed ability to detect politeness", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage locates the explanation in the user's own habits, not in any capability of the chatbot itself." },
      { text: "A legal requirement to be polite to AI systems", errorType: "outside_knowledge_not_supported_by_passage", why: "No legal requirement is discussed in the passage." },
      { text: "A widespread fear that the chatbot might actually be conscious", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states users know the chatbot isn't conscious, so fear of its consciousness isn't the explanation given." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_anthropomorphism",
    stem: "According to the passage, under the self-regulation explanation, anthropomorphizing a chatbot is best understood as:",
    reasoning: "The passage states this is 'less a mistake about what the chatbot is and more a decision about what kind of person the user wants to remain.'",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "A decision about what kind of person the user wants to remain", correct: true },
      { text: "A factual mistake about the chatbot's inner life", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly frames this explanation as 'less a mistake' about the chatbot, contradicting this option." },
      { text: "Evidence that the user has been deceived by the chatbot's design", errorType: "outside_knowledge_not_supported_by_passage", why: "Deception by design isn't part of the self-regulation explanation the passage describes." },
      { text: "An entirely involuntary reflex with no connection to the user's values", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames this as a meaningful 'decision' connected to the user's values, not an involuntary reflex disconnected from them." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_anthropomorphism",
    stem: "Which finding would most directly support the passage's self-regulation explanation over the simple-confusion explanation?",
    reasoning: "If users who fully and explicitly understand a chatbot is not conscious still remain polite to it (rather than dropping politeness once confusion is ruled out), this would support the idea that the politeness serves the user's own self-regulation, not a mistaken belief about the chatbot.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Users who clearly understand and can articulate that the chatbot is not conscious remain just as polite to it as users who are less certain", correct: true },
      { text: "Users become ruder to chatbots the longer they use them", errorType: "true_statement_that_does_not_answer_the_question", why: "A change over time doesn't specifically distinguish between the confusion and self-regulation explanations." },
      { text: "Chatbots that respond with simulated gratitude are rated as more helpful", errorType: "true_statement_that_does_not_answer_the_question", why: "Perceived helpfulness of the chatbot's responses doesn't test why the user is polite in the first place." },
      { text: "Younger users are more likely to use voice assistants than older users", errorType: "outside_knowledge_not_supported_by_passage", why: "Age-related adoption rates don't bear on which explanation for politeness is correct." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_anthropomorphism",
    stem: "According to the passage, many users report feeling:",
    reasoning: "The passage states many users 'report genuine discomfort at the idea of being rude to it [the chatbot].'",
    difficulty: 0.1,
    sirs: 1,
    options: [
      { text: "Genuine discomfort at the idea of being rude to a chatbot", correct: true },
      { text: "Complete indifference to how they speak to a chatbot", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly describes discomfort, not indifference." },
      { text: "Anger that chatbots exist at all", errorType: "outside_knowledge_not_supported_by_passage", why: "Anger about chatbots' existence is not discussed in the passage." },
      { text: "Confusion about how to operate a chatbot's interface", errorType: "outside_knowledge_not_supported_by_passage", why: "Interface usability is not the topic of the passage; the discomfort concerns politeness, not operation difficulty." },
    ],
  },

  // --- cars_gift_economics (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_gift_economics",
    stem: "According to the passage, the standard economic calculation finds that gift-giving produces:",
    reasoning: "The passage states this calculation finds gift-giving produces 'on average, less satisfaction per dollar than if the recipient had simply been given cash.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Less satisfaction per dollar than giving cash instead", correct: true },
      { text: "More satisfaction per dollar than giving cash instead", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage states the standard calculation finds the opposite — less satisfaction than cash, not more." },
      { text: "Exactly the same satisfaction per dollar as giving cash", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly describes an inefficiency, a difference in satisfaction, not equivalence." },
      { text: "No measurable satisfaction at all for either giver or recipient", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses relative satisfaction levels, not a complete absence of satisfaction." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_gift_economics",
    stem: "The passage's alternative account holds that a gift's value lies substantially in:",
    reasoning: "The passage states the value lies in 'what choosing it reveals about the giver's attention to the recipient's particular tastes' — a signal cash cannot send.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "What choosing the gift reveals about the giver's attention to the recipient's tastes", correct: true },
      { text: "The exact monetary value of the item given", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's alternative account focuses on the signal of attention conveyed, not simply the item's price." },
      { text: "How quickly the gift can be exchanged or returned", errorType: "outside_knowledge_not_supported_by_passage", why: "Return policies are not discussed in the passage." },
      { text: "Whether the gift was purchased on sale", errorType: "outside_knowledge_not_supported_by_passage", why: "Sale pricing is not part of the passage's argument about signaling value." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_gift_economics",
    stem: "According to the passage, cash cannot send the same signal as a thoughtful gift because cash:",
    reasoning: "The passage states this is 'precisely because it requires no such attention' — cash requires no engagement with the recipient's particular tastes, unlike selecting a specific gift.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Requires no attention to the recipient's particular tastes", correct: true },
      { text: "Is illegal to give as a gift in most contexts", errorType: "outside_knowledge_not_supported_by_passage", why: "Legality of giving cash is not discussed in the passage." },
      { text: "Is always worth less than a physical gift of equivalent price", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's argument is about the signal sent, not a claim that cash is worth objectively less in value." },
      { text: "Cannot be exchanged for goods the recipient actually wants", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's standard economic view actually assumes cash lets recipients get exactly what they want; the point about cash is that it requires no attention, not that it's less useful." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_gift_economics",
    stem: "Which finding would most directly challenge the passage's alternative (signaling) account of gift-giving?",
    reasoning: "The signaling account depends on gifts conveying information about the giver's attentiveness that cash cannot; a finding that recipients value cash gifts from close, attentive givers just as highly as thoughtful physical gifts would undercut the claim that gifts uniquely carry this signal.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Recipients report valuing a cash gift from a close friend just as much as a thoughtfully chosen physical gift from the same friend", correct: true },
      { text: "Recipients report enjoying receiving gifts more than receiving cash from strangers", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "A comparison specifically involving strangers doesn't address the signaling account's claim about attentive givers, which the passage's argument centers on." },
      { text: "Givers report spending more time selecting gifts for close friends than for acquaintances", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "This is actually consistent with, not a challenge to, the passage's signaling account." },
      { text: "Most gifts given during holidays cost less than $50", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Price point alone doesn't bear on whether gifts send a signal cash cannot." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_gift_economics",
    stem: "According to the passage, the 'inefficiency' economists measure in gift-giving is reframed by the alternative account as:",
    reasoning: "The passage's closing line states this 'inefficiency' is 'not a flaw in gift-giving but the cost of purchasing a signal that a more efficient transfer could never provide.'",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "The cost of purchasing a signal that a more efficient transfer (like cash) could never provide", correct: true },
      { text: "Clear proof that gift-giving is an irrational practice that should be abandoned", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly reframes the inefficiency as reasonable, not as proof gift-giving is irrational." },
      { text: "A sign that givers do not actually care about their recipients", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's alternative account suggests the opposite — that gift choice reflects care and attention to the recipient." },
      { text: "Evidence that cash is always the worse gift option in every circumstance", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage doesn't claim cash is always worse; it explains why non-cash gifts can carry additional value in some cases via signaling." },
    ],
  },

  // --- cars_collective_memory (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_collective_memory",
    stem: "According to the passage, outsiders have often assumed that communities without written records possess:",
    reasoning: "The passage states outsiders have assumed such communities possess 'only a hazy, unreliable sense of their own past.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Only a hazy, unreliable sense of their own past", correct: true },
      { text: "A more reliable historical record than written cultures", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the common outsider assumption as the opposite — that oral tradition is less reliable, not more." },
      { text: "No interest whatsoever in preserving their own history", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't attribute a lack of interest to these communities; it discusses an assumption about reliability, not motivation." },
      { text: "Written records that have simply been lost over time", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses communities without written records at all, not communities whose written records were lost." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_collective_memory",
    stem: "According to the passage, anthropologists have documented that oral genealogies can remain stable due to:",
    reasoning: "The passage attributes this stability to 'formal recitation practices, communal correction of errors during retelling, and social investment in getting the account right.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Formal recitation practices and communal correction of errors", correct: true },
      { text: "The complete absence of any social pressure around retelling", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage credits social investment and communal correction, meaning social pressure/investment, not its absence, contributes to stability." },
      { text: "Random chance alone, unrelated to any institutional practice", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage attributes stability to specific institutional practices, not to random chance." },
      { text: "Strict government regulation of storytelling", errorType: "outside_knowledge_not_supported_by_passage", why: "Government regulation is not discussed in the passage; the mechanisms described are communal, not governmental." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_collective_memory",
    stem: "The passage's discussion of stable oral traditions is used to argue that a historical record's reliability depends on:",
    reasoning: "The passage concludes reliability 'depends less on whether it is written or spoken and more on whether a community has built institutions...dedicated to checking and preserving it.'",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Whether a community has built institutions to check and preserve the record, regardless of written or oral form", correct: true },
      { text: "Whether the record was written down at the exact time of the events described", correct: false, errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly argues reliability doesn't hinge on written versus oral form at all." },
      { text: "The total population size of the community keeping the record", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Population size is not a factor the passage discusses in relation to record reliability." },
      { text: "Whether the events described were witnessed by a government official", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Official witnessing is not a criterion the passage raises for reliability." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_collective_memory",
    stem: "Based on the passage's argument, which written historical record would be predicted to be least reliable?",
    reasoning: "Since the passage argues reliability depends on institutional checking and preservation practices rather than the written/oral distinction itself, a written record produced by a single author with no independent verification or communal correction would be predicted to be less reliable than one with such institutional checks, despite being written.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "A private diary written by a single individual, never reviewed or cross-checked by anyone else", correct: true },
      { text: "An oral genealogy recited formally at community gatherings and corrected by elders when errors occur", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage explicitly describes this kind of communal-checking process as supporting reliability, not undermining it, regardless of its oral form." },
      { text: "A government archive maintained by multiple official record-keepers", errorType: "outside_knowledge_not_supported_by_passage", why: "Multiple record-keepers checking a record aligns with the passage's institutional-checking criterion for reliability, not against it." },
      { text: "A peer-reviewed historical academic publication", errorType: "outside_knowledge_not_supported_by_passage", why: "Peer review is itself an institutional-checking mechanism, which the passage's argument suggests would support reliability." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_collective_memory",
    stem: "According to the passage, the assumption that oral transmission is 'obviously more prone to distortion' than a written text is described as:",
    reasoning: "The passage introduces this assumption and then states anthropologists studying actual oral tradition 'have complicated this assumption' — meaning the assumption is challenged, not confirmed, by the evidence presented.",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "Complicated by anthropological evidence of stable oral traditions", correct: true },
      { text: "Strongly confirmed by every documented case of oral tradition", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage states this assumption is complicated, i.e., challenged, not confirmed, by anthropological evidence." },
      { text: "Irrelevant to the passage's overall argument", errorType: "passage_detail_misread_or_over_extrapolated", why: "This assumption is actually central to the passage's argument, serving as the claim the passage goes on to challenge." },
      { text: "A view held only by anthropologists themselves", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage attributes this assumption to outsiders generally, and states anthropologists are the ones who complicate it, not who hold it." },
    ],
  },

  // --- cars_imperfection_aesthetics (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_imperfection_aesthetics",
    stem: "According to the passage, certain aesthetic traditions treat a visible flaw as:",
    reasoning: "The passage states these traditions treat the imperfection 'as part of the object's value rather than a defect to be concealed.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Part of the object's value, not a defect to conceal", correct: true },
      { text: "A defect that must always be hidden from view", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly describes these traditions as doing the opposite — making the flaw visible rather than hiding it." },
      { text: "Evidence that the object should be discarded", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the flaw as adding value, not as a reason to discard the object." },
      { text: "A sign of poor craftsmanship by the maker", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames the flaw as intentionally incorporated and valued, not as evidence of poor craftsmanship." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_imperfection_aesthetics",
    stem: "The passage argues that a 'purely functional account' struggles to explain the appeal of visible imperfection because the flaw:",
    reasoning: "The passage states this account struggles 'since the flaw contributes nothing to the object's use' — a functional account can't explain value added by something that doesn't affect usability.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Contributes nothing to the object's practical use", correct: true },
      { text: "Makes the object function better than before", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states the flaw contributes nothing to use, not that it improves function." },
      { text: "Is always more expensive to create deliberately", errorType: "outside_knowledge_not_supported_by_passage", why: "Cost of creating the flaw is not the issue the passage raises about the functional account." },
      { text: "Cannot be perceived by most observers", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses visible flaws that are clearly perceptible, not imperceptible ones." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_imperfection_aesthetics",
    stem: "According to the passage, the more promising account holds that a visible imperfection serves as:",
    reasoning: "The passage states the imperfection serves 'as a record of the object's particular history — its making, its use, its survival.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "A record of the object's particular history", correct: true },
      { text: "A random, meaningless byproduct of the manufacturing process", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's more promising account treats the flaw as meaningful evidence, not as random and meaningless." },
      { text: "A guarantee of the object's future durability", errorType: "outside_knowledge_not_supported_by_passage", why: "Future durability is not the function the passage assigns to the visible imperfection." },
      { text: "Proof that the object is a forgery", errorType: "outside_knowledge_not_supported_by_passage", why: "Authentication or forgery detection is not discussed in the passage." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_imperfection_aesthetics",
    stem: "Based on the passage's 'more promising account,' which object would be predicted to be valued most highly for its visible imperfection?",
    reasoning: "Since the account values imperfection as a record of an object's actual history of making, use, and survival, an object whose visible flaw genuinely resulted from real use and repair over time would fit the account better than an artificially added flaw with no real history behind it.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "A ceramic bowl with a crack that was actually repaired with gold lacquer after years of real use", correct: true },
      { text: "A brand-new bowl manufactured with a fake crack pattern printed on by machine, with no history of actual use", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's account values a flaw as evidence of genuine history; a machine-printed fake pattern with no real use history doesn't fit that account as well." },
      { text: "A perfectly symmetrical, flawless bowl with no visible marks at all", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's account specifically concerns valuing visible imperfection, which this flawless object lacks entirely." },
      { text: "A bowl described in an advertisement as 'imperfect' without any actual visible flaw", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's account is about actual visible marks serving as a genuine historical record, not marketing language alone." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_imperfection_aesthetics",
    stem: "According to the passage, the more promising account converts a mark of wear into:",
    reasoning: "The passage states this account converts a mark of wear 'into a kind of evidence that the object has actually lived a life rather than merely existing as an interchangeable specimen of its type.'",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "Evidence that the object has lived a life, rather than being an interchangeable specimen", correct: true },
      { text: "Proof that the object is defective and should be replaced", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames the mark positively as evidence of a lived history, not as proof of a defect requiring replacement." },
      { text: "A sign that the object was mass-produced on an assembly line", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's account contrasts individual history with being an 'interchangeable specimen,' the opposite of what mass production implies." },
      { text: "An indication that the object's owner did not care for it properly", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't frame the mark as evidence of poor care; it frames it as evidence of a meaningful history of use." },
    ],
  },

  // --- cars_rhetoric_of_apology (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_rhetoric_of_apology",
    stem: "According to the passage, public apologies are often criticized as insincere even when they include:",
    reasoning: "The passage states apologies are criticized as insincere 'even when they include the expected components — an acknowledgment of wrongdoing, an expression of regret, and a statement of intent to do better.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "An acknowledgment of wrongdoing, expression of regret, and intent to do better", correct: true },
      { text: "No mention of the wrongdoing at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes apologies that do include acknowledgment of wrongdoing, yet are still criticized." },
      { text: "A large financial settlement offered immediately", errorType: "outside_knowledge_not_supported_by_passage", why: "Financial settlements are not part of the 'expected components' the passage lists." },
      { text: "A public relations team's official statement", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses the content of an apology, not who authors or delivers it." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_rhetoric_of_apology",
    stem: "The passage's account locates the missing element in judging sincerity as:",
    reasoning: "The passage states this account 'locates the missing element in costliness' — an apology is judged sincere to the extent it imposes a real cost on the person apologizing.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Costliness — whether the apology imposes some genuine cost on the speaker", correct: true },
      { text: "The specific vocabulary and word choice used", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's account focuses on real-world cost, not on which words are chosen." },
      { text: "Whether the apology is delivered in person rather than in writing", errorType: "outside_knowledge_not_supported_by_passage", why: "Delivery format is not the factor the passage's account identifies." },
      { text: "The length of time between the wrongdoing and the apology", errorType: "outside_knowledge_not_supported_by_passage", why: "Timing is not the missing element the passage's account identifies; costliness is." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_rhetoric_of_apology",
    stem: "According to the passage, a costly signal is significant because it is:",
    reasoning: "The passage states 'only a costly signal is hard for an insincere apologizer to fake cheaply' — the cost is what makes the signal credible, since a truly insincere apologizer would be unwilling to pay it.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Hard for an insincere apologizer to fake cheaply", correct: true },
      { text: "Easy for anyone, sincere or not, to produce effortlessly", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's entire point is that a costly signal is specifically NOT easy or cheap to fake, unlike a costless one." },
      { text: "Legally required in most public apologies", errorType: "outside_knowledge_not_supported_by_passage", why: "Legal requirements around apologies are not discussed in the passage." },
      { text: "Only relevant when the apology is given by a large organization", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's account applies to apologies generally, not exclusively to organizational apologies." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_rhetoric_of_apology",
    stem: "Based on the passage's account, which apology would be predicted to be received as most sincere?",
    reasoning: "Consistent with the costliness account, an apology accompanied by a real, difficult-to-fake sacrifice (such as voluntarily stepping down from a position) would be predicted to be received as more sincere than one that costs the speaker nothing beyond words.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "An executive who publicly apologizes and voluntarily resigns from a well-paid position as a result", correct: true },
      { text: "An executive who reads a brief written apology statement with no other consequence to themselves", errorType: "outside_knowledge_not_supported_by_passage", why: "Per the passage's account, an apology costing the speaker nothing is predicted to be received as merely strategic, not especially sincere." },
      { text: "An executive who apologizes using unusually eloquent and carefully crafted language", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's account locates sincerity in real cost, not in the eloquence or craft of the language used." },
      { text: "An executive who apologizes only after being legally compelled to do so", errorType: "outside_knowledge_not_supported_by_passage", why: "Legal compulsion doesn't represent a voluntary costly signal from the speaker in the sense the passage describes." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_rhetoric_of_apology",
    stem: "According to the passage, an apology that costs the speaker nothing beyond the words themselves will tend to be received as:",
    reasoning: "The passage states such an apology 'will tend to be received as strategic regardless of how carefully its language is crafted.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Strategic, regardless of how carefully its language is crafted", correct: true },
      { text: "Deeply sincere, if the language is sufficiently well-crafted", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states careful language crafting doesn't change this outcome — it will still be seen as strategic." },
      { text: "Legally binding on the speaker", errorType: "outside_knowledge_not_supported_by_passage", why: "Legal bindingness is not a topic the passage discusses in relation to apology reception." },
      { text: "Impossible for listeners to evaluate at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes listeners as actively judging (and finding lacking) apologies with no real cost, not as unable to evaluate them." },
    ],
  },

  // --- cars_maps_and_power (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_maps_and_power",
    stem: "According to the passage, a map is often treated as:",
    reasoning: "The passage opens by stating a map 'is often treated as a neutral, technical translation of physical space onto paper, faithful to the terrain it represents.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "A neutral, technical translation of physical space, faithful to the terrain", correct: true },
      { text: "An explicitly biased political statement by its very nature", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the common view of maps as neutral, which it then goes on to challenge — this option describes the challenge, not the common assumption being stated here." },
      { text: "A form of art with no practical function", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses maps' practical, technical function, not their status as art." },
      { text: "An outdated technology replaced entirely by GPS", errorType: "outside_knowledge_not_supported_by_passage", why: "GPS and technological obsolescence are not discussed in the passage." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_maps_and_power",
    stem: "The passage argues that critical geographers have challenged the neutral view of maps by pointing out that every map involves choices dictated by:",
    reasoning: "The passage states these choices are 'not dictated by the terrain itself but by the purposes and priorities of whoever made the map.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "The purposes and priorities of whoever made the map", correct: true },
      { text: "The terrain itself, with no room for any other influence", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states these choices are 'not dictated by the terrain itself,' contradicting this option." },
      { text: "International cartography regulations", errorType: "outside_knowledge_not_supported_by_passage", why: "Regulatory standards are not discussed anywhere in the passage." },
      { text: "Random chance in the mapmaking process", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage attributes these choices to the mapmaker's purposes, not to randomness." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_maps_and_power",
    stem: "According to the passage, a map drawn to aid a colonial administration versus one drawn to aid a hiker, even of identical terrain, would:",
    reasoning: "The passage states such maps 'will foreground different features than one drawn to aid a hiker...and neither is simply \"more accurate\" in some purpose-independent sense.'",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Foreground different features, with neither being simply 'more accurate' in a purpose-independent sense", correct: true },
      { text: "Be identical in every respect, since the terrain itself is the same", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly argues these maps would differ in what they foreground, despite depicting the same terrain." },
      { text: "Both be equally useless for any practical purpose", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames each map as suited to its particular purpose, not as universally useless." },
      { text: "Differ only in their choice of paper size", errorType: "outside_knowledge_not_supported_by_passage", why: "Paper size is a trivial detail not discussed in the passage; the relevant difference is which features are foregrounded." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_maps_and_power",
    stem: "Which finding would most directly support the passage's argument that cartography is 'an inherently rhetorical practice'?",
    reasoning: "The passage's argument depends on maps making implicit arguments through selective inclusion; evidence that maps of the same region drawn for different purposes systematically omit or emphasize different features in ways that serve each map's purpose would directly support this rhetorical framing.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Maps of the same city produced for tourists versus for city planners consistently emphasize different features relevant to each group's goals", correct: true },
      { text: "All maps of a given region, regardless of purpose, include exactly the same set of features", errorType: "outside_knowledge_not_supported_by_passage", why: "Identical content regardless of purpose would undercut, not support, the passage's argument that map choices reflect purpose-driven selection." },
      { text: "Modern maps are printed using higher-resolution printing technology than older maps", errorType: "outside_knowledge_not_supported_by_passage", why: "Printing resolution is a technical detail unrelated to the rhetorical, purpose-driven selection argument the passage makes." },
      { text: "Most people cannot accurately read a topographic map without training", errorType: "outside_knowledge_not_supported_by_passage", why: "General map-reading literacy doesn't bear on whether maps make purpose-driven rhetorical choices." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_maps_and_power",
    stem: "According to the passage, this reframing means a map does not just show where things are — it also:",
    reasoning: "The passage's final sentence states a map 'argues, through its selective inclusions, for a particular way of understanding a place.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Argues, through selective inclusion, for a particular way of understanding a place", correct: true },
      { text: "Guarantees a single, universally correct interpretation of a place", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's argument is that maps offer one purpose-driven perspective among possible others, not a single universally correct interpretation." },
      { text: "Eliminates the need for any other historical documentation of a place", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't discuss maps replacing other historical documentation." },
      { text: "Remains completely free of the mapmaker's own perspective", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's entire argument is that maps do reflect the mapmaker's perspective and purposes, not that they're free of it." },
    ],
  },
];
