import type { ItemDef } from "./types";

export const itemsCars4: ItemDef[] = [
  // --- cars_nudge_ethics (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_nudge_ethics",
    stem: "According to the passage, defenders of nudges argue this approach respects autonomy because:",
    reasoning: "The passage states defenders argue this 'because every option remains available.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Every option remains technically available to the person", correct: true },
      { text: "Nudges always involve financial incentives", errorType: "outside_knowledge_not_supported_by_passage", why: "Financial incentives are not the defense the passage attributes to nudge supporters; option availability is." },
      { text: "Nudges are required by law in most institutions", errorType: "outside_knowledge_not_supported_by_passage", why: "Legal requirements are not discussed in the passage as the basis for the autonomy defense." },
      { text: "People are always explicitly told about the nudge being used on them", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's defense centers on preserved option availability, not on explicit disclosure of the nudge." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_nudge_ethics",
    stem: "According to the passage, critics argue that the 'you could still say no' defense of nudging:",
    reasoning: "The passage states critics argue 'the fact that refusal remains technically possible has never been sufficient to excuse manipulation in other contexts, such as deceptive advertising.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Has never been sufficient to excuse manipulation in other contexts, like deceptive advertising", correct: true },
      { text: "Is a completely new and unprecedented ethical argument never used before", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly compares this defense to its use (and rejection) in other established contexts like deceptive advertising, not treating it as unprecedented." },
      { text: "Is universally accepted by all ethicists as sufficient justification", errorType: "sign_or_direction_reversal", why: "The passage presents critics as rejecting, not universally accepting, this defense." },
      { text: "Only applies to nudges used by governments, not private companies", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't restrict this critique to government nudges specifically; it discusses the defense's logic generally." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_nudge_ethics",
    stem: "According to the passage, the real dispute over nudges is described as being about:",
    reasoning: "The passage states 'the dispute...is not really about whether nudges work, but about whether \"you could still say no\" is actually doing the ethical work defenders assume it does.'",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Whether 'you could still say no' actually does the ethical work defenders assume", correct: true },
      { text: "Whether nudges are effective at changing behavior at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states the dispute is 'not really about whether nudges work,' ruling out effectiveness as the real point of contention." },
      { text: "Whether nudges are more expensive than traditional regulation", errorType: "outside_knowledge_not_supported_by_passage", why: "Cost comparisons to regulation are not discussed in the passage as the substance of the dispute." },
      { text: "Whether nudges should be replaced entirely by direct legal mandates", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage frames the dispute as conceptual/ethical (about the autonomy defense), not about a policy choice between nudges and legal mandates." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_nudge_ethics",
    stem: "Which finding would most directly support the critics' position described in the passage?",
    reasoning: "The critics' argument is that 'you could still say no' fails to excuse manipulation, drawing an analogy to deceptive advertising; evidence that people exposed to a nudge feel deceived or resentful upon learning about it — similar to reactions to discovered deceptive advertising — would support the critics' analogy.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "People who learn they were nudged report feeling deceived, similar to reactions when deceptive advertising is exposed", correct: true },
      { text: "People who are nudged make decisions faster than people who are not", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "Decision speed doesn't address the ethical question of whether the autonomy defense is doing genuine ethical work." },
      { text: "Nudges are used more frequently in retirement savings programs than in cafeterias", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Frequency of use in different domains doesn't bear on the ethical critique the passage describes." },
      { text: "People who are nudged toward healthy food report enjoying the food they chose", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "Enjoyment of the outcome doesn't address whether the underlying nudging process was ethically manipulative, which is the critics' concern." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_nudge_ethics",
    stem: "According to the passage, a nudge is defined as a change to:",
    reasoning: "The passage states nudges are 'changes to how choices are presented...to influence behavior without restricting anyone's options or changing the underlying incentives.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "How choices are presented, without restricting options or changing incentives", correct: true },
      { text: "The legal penalties associated with a choice", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states nudges work without changing underlying incentives, which would include penalties." },
      { text: "The actual set of options available to a person", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states nudges work 'without restricting anyone's options,' not by changing the option set itself." },
      { text: "The price of every available option", correct: false, errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states nudges operate without changing underlying incentives such as price." },
    ],
  },

  // --- cars_problem_of_induction (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_problem_of_induction",
    stem: "According to the passage, Hume observed that inductive inference cannot be justified by:",
    reasoning: "The passage states Hume observed 'this inference cannot itself be justified by logic alone, since no number of past instances logically guarantees a future one.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Logic alone, since past instances don't logically guarantee a future one", correct: true },
      { text: "Any form of observation whatsoever", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's point is specifically about the limits of logical justification, not a claim that observation itself is impossible or useless." },
      { text: "Mathematical proof involving imaginary numbers", errorType: "outside_knowledge_not_supported_by_passage", why: "Imaginary numbers are not discussed in the passage; the issue concerns logical justification of inductive inference generally." },
      { text: "Appeal to religious authority", errorType: "outside_knowledge_not_supported_by_passage", why: "Religious authority is not the justification method the passage discusses as failing; logical guarantee from past instances is." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_problem_of_induction",
    stem: "According to the passage, appealing to induction's past success to justify induction itself would be:",
    reasoning: "The passage states this would be circular, since it 'circularly assum[es] the very principle in question' — using induction to justify induction.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Circular, since it assumes the very principle being justified", correct: true },
      { text: "A valid, non-circular way of justifying induction", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly identifies this move as circular, not as a valid, independent justification." },
      { text: "Something Hume never considered as a possible justification", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage explicitly discusses and rejects this exact justification attempt as part of the argument, meaning it was considered." },
      { text: "The strongest possible argument in favor of induction", errorType: "sign_or_direction_reversal", why: "The passage presents this as a flawed, circular argument, not the strongest possible justification." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_problem_of_induction",
    stem: "According to the passage, some people conclude the problem of induction is:",
    reasoning: "The passage states this view holds the problem is 'more a puzzle for philosophers than a practical difficulty for scientists,' given science's practical success.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "More a puzzle for philosophers than a practical difficulty for scientists", correct: true },
      { text: "A problem that has completely stopped scientific progress", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states the problem 'has not stopped science from working remarkably well in practice.'" },
      { text: "Entirely solved and no longer a matter of any debate", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage presents ongoing disagreement (some view it as a mere puzzle, others as a real, consequential gap), not universal resolution." },
      { text: "A problem unique to biology, not applicable to other sciences", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses inductive reasoning in science generally, not a claim restricted to biology specifically." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_problem_of_induction",
    stem: "Based on the passage, the view that the problem of induction is 'real and consequential' would most directly support which conclusion about scientific laws?",
    reasoning: "The passage states this view holds that confidence in scientific laws 'ultimately rests on an assumption...that cannot itself be proven, only presupposed' — meaning even our best-confirmed scientific laws carry an irreducible, unprovable assumption at their foundation.",
    difficulty: 0.5,
    sirs: 3,
    options: [
      { text: "Even well-confirmed scientific laws rest on an assumption that cannot itself be proven", correct: true },
      { text: "Scientific laws are proven with the same certainty as mathematical theorems", errorType: "outside_knowledge_not_supported_by_passage", why: "This view explicitly holds the opposite — that scientific laws rest on an unprovable assumption, unlike mathematical proof." },
      { text: "Scientific laws should be abandoned entirely since they cannot be justified", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't suggest abandoning scientific laws; it describes an epistemological limitation to their justification, not a call to discard them." },
      { text: "The problem of induction only affects laws that have not yet been tested at all", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage explicitly extends the problem to 'any scientific law, however well-confirmed,' not only untested ones." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_problem_of_induction",
    stem: "According to the passage, scientific reasoning routinely infers general laws from:",
    reasoning: "The passage states scientific reasoning 'routinely infers general laws from a finite set of past observations.'",
    difficulty: 0.1,
    sirs: 1,
    options: [
      { text: "A finite set of past observations", correct: true },
      { text: "An infinite set of all possible future observations", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly describes a finite set of past observations, not an infinite set of future ones." },
      { text: "Purely mathematical axioms with no empirical component", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses empirical, observation-based inference, not purely axiomatic mathematical reasoning." },
      { text: "A single isolated observation only", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage refers to inferring laws from a 'set' of observations, implying multiple instances, not a single isolated one." },
    ],
  },

  // --- cars_value_of_boredom (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_value_of_boredom",
    stem: "According to the passage, boredom is typically treated as:",
    reasoning: "The passage states boredom 'is typically treated as an unpleasant state to be eliminated as quickly as possible.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "An unpleasant state to be eliminated as quickly as possible", correct: true },
      { text: "A valuable emotion that should be actively cultivated", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes this valuing of boredom as the alternative view psychologists propose, not the typical treatment of it." },
      { text: "A rare emotion that most people never experience", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't characterize boredom as rare; it discusses it as a common experience people seek to eliminate." },
      { text: "A physical illness requiring medical treatment", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses boredom as a psychological state, not a physical illness." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_value_of_boredom",
    stem: "According to the passage, some psychologists argue boredom may function as a signal that:",
    reasoning: "The passage states boredom may signal 'that one's current activity is failing to use one's capacities or is misaligned with one's goals.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "The current activity fails to use one's capacities or is misaligned with one's goals", correct: true },
      { text: "A person needs immediate medical attention", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage frames boredom as a psychological signal about activity alignment, not a medical warning sign." },
      { text: "A person's phone battery is about to die", errorType: "outside_knowledge_not_supported_by_passage", why: "This is an absurd, unrelated claim not present anywhere in the passage." },
      { text: "A person has achieved complete mastery of a skill", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage frames boredom as signaling misalignment or underuse of capacities, not achievement of mastery specifically." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_value_of_boredom",
    stem: "According to the passage, habitually escaping boredom the instant it arises:",
    reasoning: "The passage states this 'does not solve the problem boredom is signaling; it simply mutes the signal, leaving the underlying misalignment...unaddressed and undiscovered.'",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Mutes the signal without solving the underlying misalignment it points to", correct: true },
      { text: "Permanently and effectively solves the problem the boredom was signaling", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states this escape 'does not solve the problem,' contradicting this option." },
      { text: "Causes the underlying misalignment to worsen dramatically over time", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage states the misalignment remains 'unaddressed and undiscovered,' not that it necessarily worsens dramatically." },
      { text: "Has no effect on the signal or the underlying problem at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states escaping boredom does have an effect — muting the signal — even though it doesn't solve the underlying problem." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_value_of_boredom",
    stem: "Based on the passage's argument, which finding would most directly support the view that boredom serves a useful signaling function?",
    reasoning: "The passage's argument is that boredom prompts a search for more meaningfully engaging activity when heeded; evidence that people who tolerate boredom (rather than immediately escaping it) subsequently find more personally fulfilling activities would directly support this signaling-function account.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "People who tolerate boredom rather than immediately escaping it are more likely to later find more personally fulfilling activities", correct: true },
      { text: "People who use their phones frequently report feeling less bored overall", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "Reduced immediate boredom from phone use doesn't test whether tolerating (rather than escaping) boredom leads to discovering better-aligned activities." },
      { text: "Boredom is reported more frequently on weekdays than weekends", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "A weekday/weekend pattern doesn't test the passage's specific claim about boredom's signaling function and its usefulness when tolerated." },
      { text: "People rate boredom as one of the least pleasant emotions they experience", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "Unpleasantness of boredom is consistent with the passage's opening premise but doesn't test the specific signaling-function claim." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_value_of_boredom",
    stem: "According to the passage, modern devices make near-constant elimination of boredom:",
    reasoning: "The passage states modern devices make this elimination 'technically available,' meaning readily accessible whenever a person wants it.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Technically available at nearly any time", correct: true },
      { text: "Completely impossible to achieve", errorType: "sign_or_direction_reversal", why: "The passage states the opposite — that devices make constant elimination of boredom readily available, not impossible." },
      { text: "Illegal in most workplace settings", errorType: "outside_knowledge_not_supported_by_passage", why: "Legality of device use in workplaces is not discussed in the passage." },
      { text: "Only available to people with certain jobs", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't restrict this availability to specific job types; it describes modern devices generally." },
    ],
  },

  // --- cars_algorithmic_taste (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_algorithmic_taste",
    stem: "According to the passage, critics worry that recommendation algorithms create a feedback loop that:",
    reasoning: "The passage states critics worry this 'narrows taste over time,' since a system trained on existing preferences keeps recommending similar content.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Narrows a user's taste over time", correct: true },
      { text: "Broadens a user's taste dramatically over time", errorType: "sign_or_direction_reversal", why: "The passage describes critics' concern as narrowing, not broadening, of taste over time." },
      { text: "Has no measurable effect on user preferences at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes a specific, measurable concern (narrowing), not an absence of effect." },
      { text: "Only affects users who watch content for more than ten hours per week", errorType: "outside_knowledge_not_supported_by_passage", why: "No specific usage-hour threshold is discussed in the passage." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_algorithmic_taste",
    stem: "According to the passage, defenders of recommendation algorithms respond to the narrowing-taste concern by arguing that:",
    reasoning: "The passage states defenders argue the concern 'assumes an unrealistic alternative...when in practice most people, left to their own devices, gravitate toward the familiar anyway.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "The concern assumes an unrealistic alternative, since people gravitate toward the familiar anyway", correct: true },
      { text: "Algorithms are legally required to promote diverse content", errorType: "outside_knowledge_not_supported_by_passage", why: "Legal requirements are not part of the defenders' argument as described in the passage." },
      { text: "Users never actually watch the content that is recommended to them", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't suggest users ignore recommendations; the concern (and the response to it) both assume recommendations are followed." },
      { text: "Algorithms are incapable of learning user preferences accurately", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's premise is that algorithms DO learn preferences (accurately enough to reinforce them), which is exactly the basis of the original concern." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_algorithmic_taste",
    stem: "According to the passage, defenders argue that blaming the algorithm 'conveniently locates the problem' in:",
    reasoning: "The passage states this framing locates the problem 'in the technology rather than in the more uncomfortable possibility that unlimited choice was never going to produce adventurous taste on its own.'",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "The technology, rather than in the more uncomfortable possibility about human tendencies toward the familiar", correct: true },
      { text: "The user's own conscious, deliberate choices", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's framing is about locating blame in the technology, as an alternative to a broader claim about human tendencies, not specifically about deliberate user choice." },
      { text: "Government regulation of streaming platforms", errorType: "outside_knowledge_not_supported_by_passage", why: "Government regulation is not discussed in the passage as a location where blame is placed." },
      { text: "The high cost of streaming subscriptions", errorType: "outside_knowledge_not_supported_by_passage", why: "Subscription cost is not discussed anywhere in the passage." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_algorithmic_taste",
    stem: "Which finding would most directly support the defenders' position described in the passage?",
    reasoning: "Defenders argue people gravitate toward the familiar even without algorithmic influence; evidence that users browsing a large, non-personalized catalog (no algorithm involved) still overwhelmingly choose familiar content would directly support this claim, showing the narrowing tendency isn't algorithm-specific.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Users browsing a large, non-personalized catalog with no recommendation algorithm still overwhelmingly choose familiar types of content", correct: true },
      { text: "Streaming platforms have increased their total number of recommendation algorithms in recent years", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "The number of algorithms used doesn't address whether narrowing taste is caused by algorithms specifically or reflects a pre-existing human tendency." },
      { text: "Users who unsubscribe from a streaming service report saving money", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Financial savings from unsubscribing is irrelevant to the debate about whether algorithms or inherent human tendencies drive narrowing taste." },
      { text: "Recommendation algorithms have become more computationally efficient over time", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Computational efficiency doesn't address the substantive question of whether algorithms cause narrowing taste or merely reflect pre-existing tendencies." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_algorithmic_taste",
    stem: "According to the passage, streaming platforms recommend content based on:",
    reasoning: "The passage states platforms recommend content 'based on a user's past behavior.'",
    difficulty: 0.1,
    sirs: 1,
    options: [
      { text: "A user's past behavior", correct: true },
      { text: "Random selection with no reference to the user at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly describes recommendations as based on past behavior, not random selection." },
      { text: "A panel of human editors reviewing each user's profile individually", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage describes algorithmic, not human-editor-based, recommendation." },
      { text: "The preferences of the user's immediate family members only", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage attributes recommendations to the individual user's own past behavior, not specifically to family members' preferences." },
    ],
  },

  // --- cars_long_term_promises (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_long_term_promises",
    stem: "According to the passage, a long-term promise asks a person to commit:",
    reasoning: "The passage states such a promise asks a person 'to commit not just their present self but a future self whose preferences cannot yet be known.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Not just their present self, but a future self whose preferences are unknown", correct: true },
      { text: "Only their present self, with no implication for the future at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states such promises commit a future self as well, not only the present self." },
      { text: "Only a legal entity, never an actual individual person", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses commitments made by individuals (and by extension, nations), not a claim restricted only to legal entities." },
      { text: "A person's financial assets exclusively", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses commitment of the self broadly (preferences, identity), not specifically financial assets." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_long_term_promises",
    stem: "According to the passage, the puzzle long-term promises raise is that they claim authority over a person who:",
    reasoning: "The passage states this person 'due to genuine psychological change over time, may in some meaningful sense no longer be the same person who made the commitment.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "May, due to psychological change, no longer be the same person who made the commitment", correct: true },
      { text: "Has never changed in any way since making the original promise", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's puzzle specifically depends on the person having changed, not remaining identical." },
      { text: "Explicitly consented in writing to every possible future circumstance", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's puzzle concerns unforeseeable future preferences, not a claim about explicit written consent to every circumstance." },
      { text: "Is legally a completely different individual with a new identity", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames this as a psychological, not a formal legal, change of identity." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_long_term_promises",
    stem: "According to the passage, the 'less tidy' response concludes that long-term promises are best understood as:",
    reasoning: "The passage states this response concludes such promises are 'a present self's attempt to shape the conditions under which a future, different self will have to decide,' rather than binding the future self the way an ordinary promise binds its maker.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "A present self's attempt to shape conditions for a future self's later decision", correct: true },
      { text: "Exactly identical in nature to an ordinary, short-term promise", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly distinguishes this response from treating long-term promises the same way an ordinary promise binds its maker." },
      { text: "Completely meaningless and without any real function", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage assigns this response a specific, meaningful function (shaping future conditions), not meaninglessness." },
      { text: "A response that resolves the puzzle entirely with no remaining difficulty", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage describes this as a 'less tidy' response, implying it doesn't fully or neatly resolve the puzzle." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_long_term_promises",
    stem: "Which scenario would most directly illustrate the puzzle the passage describes regarding long-term promises?",
    reasoning: "The puzzle concerns a genuine, meaningful psychological change making the promise-maker in some sense a different person; a scenario where someone's core values and personality have genuinely and substantially transformed since making a lifelong commitment directly instantiates this exact puzzle.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "A person who made a lifelong commitment finds their core values and personality have substantially changed decades later", correct: true },
      { text: "A person breaks a promise immediately after making it, with no time or change involved", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "The puzzle specifically concerns change over meaningful time; an immediate break involves no psychological change at all." },
      { text: "A person makes a promise and keeps it exactly as originally intended with no change in circumstances", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "This scenario involves no psychological change or altered circumstances, so it doesn't raise the puzzle the passage describes." },
      { text: "A person forgets they ever made a promise at all", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Simple forgetting is a memory failure, not the psychological-change puzzle about whether a changed self is bound by an earlier self's promise." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_long_term_promises",
    stem: "According to the passage, one response to the puzzle treats it as no real puzzle because people remain:",
    reasoning: "The passage states this response holds 'people remain legally and practically the same individual throughout their lives regardless of how much they change psychologically.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Legally and practically the same individual regardless of psychological change", correct: true },
      { text: "Completely unable to change psychologically over their lifetime", errorType: "passage_detail_misread_or_over_extrapolated", why: "This response acknowledges psychological change occurs but argues it doesn't affect legal/practical identity, rather than denying change happens at all." },
      { text: "Free to break any promise they choose without consequence", errorType: "outside_knowledge_not_supported_by_passage", why: "This response is about the basis for continued identity, not a claim about consequence-free promise-breaking." },
      { text: "Required by law to renew every promise annually", errorType: "outside_knowledge_not_supported_by_passage", why: "No such legal renewal requirement is discussed anywhere in the passage." },
    ],
  },

  // --- cars_authenticity_of_place (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_authenticity_of_place",
    stem: "According to the passage, tourists routinely complain when a location:",
    reasoning: "The passage states tourists 'just as routinely complain when a location seems to have been staged or commercialized for their benefit.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Seems to have been staged or commercialized for their benefit", correct: true },
      { text: "Has too few tourist attractions to visit", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses complaints about staging/commercialization, not about a lack of attractions." },
      { text: "Charges no admission fees at all", errorType: "outside_knowledge_not_supported_by_passage", why: "Admission fees are not discussed in the passage as a source of tourist complaint." },
      { text: "Is too difficult to physically travel to", errorType: "outside_knowledge_not_supported_by_passage", why: "Travel difficulty is not the complaint the passage describes; staging/commercialization is." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_authenticity_of_place",
    stem: "According to the passage, the trouble with tourists' complaint about staged authenticity is that:",
    reasoning: "The passage states 'the presence of tourists seeking authenticity is itself usually what commercializes a place,' creating a paradox where seeking authenticity undermines it.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "The presence of tourists seeking authenticity is itself usually what commercializes the place", correct: true },
      { text: "Tourists never actually want to see anything authentic", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes tourists as genuinely seeking authenticity; the trouble is their seeking undermines the very thing sought, not that they don't want it." },
      { text: "Authentic locations are always more expensive to visit than staged ones", errorType: "outside_knowledge_not_supported_by_passage", why: "Cost comparison is not the trouble the passage identifies with the authenticity complaint." },
      { text: "Local residents actively prefer to have their communities commercialized", errorType: "outside_knowledge_not_supported_by_passage", why: "Resident preferences are not discussed in the passage as the source of the paradox described." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_authenticity_of_place",
    stem: "According to the passage, some scholars conclude that 'authenticity' in tourism is best understood as:",
    reasoning: "The passage states these scholars conclude authenticity 'is not a property a place either has or lacks, but a story tourists tell about a place's relationship to its own history.'",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "A story tourists tell about a place's relationship to its own history, not a fixed property", correct: true },
      { text: "A fixed, objective property that a place either has or lacks", errorType: "sign_or_direction_reversal", why: "The passage explicitly states scholars conclude the opposite — that authenticity is not a fixed property a place either has or lacks." },
      { text: "A legal designation assigned by tourism boards", errorType: "outside_knowledge_not_supported_by_passage", why: "Legal designation by tourism boards is not discussed in the passage as the basis of this scholarly conclusion." },
      { text: "Something that can be measured precisely using a numerical scale", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage frames authenticity as an interpretive story, not a precisely measurable numerical quantity." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_authenticity_of_place",
    stem: "Based on the passage's argument, which observation would most directly support the claim that a visitor's own presence is 'already part of what they are trying to observe'?",
    reasoning: "The passage's claim is that the tourist's presence changes the very thing they seek to authentically observe; evidence that a location's character measurably shifts as soon as tourists begin visiting it — for instance, local vendors changing their offerings specifically in response to visitor presence — would directly support this self-undermining dynamic.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "A neighborhood's local shops begin changing their offerings specifically in response to growing tourist visits, altering the very character visitors came to see", correct: true },
      { text: "A neighborhood's population size stays exactly the same before and after becoming a tourist destination", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Unchanged population size doesn't illustrate the specific claim about visitor presence altering the observed character of a place." },
      { text: "Tourists spend more money in destinations widely advertised as 'authentic'", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "Spending patterns don't address whether the visitor's own presence changes what is being observed." },
      { text: "Local residents are unaware that tourists visit their neighborhood at all", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "If residents were entirely unaware of tourism, this would actually undercut, not support, the claim that visitor presence changes the observed place." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_authenticity_of_place",
    stem: "According to the passage, the sought-after authentic version of a location often only existed:",
    reasoning: "The passage states this version 'often only ever existed before tourism discovered it, if it existed in the specific form imagined at all.'",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "Before tourism discovered the location, if it existed in that form at all", correct: true },
      { text: "After tourism developed the location fully", errorType: "sign_or_direction_reversal", why: "The passage locates the sought-after authentic version before, not after, tourism's arrival." },
      { text: "In a form that is easily reconstructed for visitors today", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage suggests this authentic version may not be reconstructible or may not have existed in the imagined form at all, not that it's easily reconstructed." },
      { text: "Only in the imagination of local government officials", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't attribute the imagined authentic version specifically to government officials; it discusses tourists' general expectations." },
    ],
  },

  // --- cars_queuing_economics (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_queuing_economics",
    stem: "According to the passage, a line at a popular restaurant is, from an economic perspective, a form of price paid in:",
    reasoning: "The passage states a line is 'a form of price paid in time rather than money.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Time, rather than money", correct: true },
      { text: "Money, rather than time", errorType: "sign_or_direction_reversal", why: "The passage explicitly states the opposite — that the price is paid in time, not money." },
      { text: "Social reputation", errorType: "outside_knowledge_not_supported_by_passage", why: "Social reputation is not the currency the passage identifies; time is." },
      { text: "Physical effort exerted while standing", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's economic framing is specifically about time as the rationing currency, not physical exertion." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_queuing_economics",
    stem: "According to the passage, this substitution (queuing instead of raising prices) is not neutral between customers because:",
    reasoning: "The passage states this is because 'time and money are not equally scarce for everyone,' meaning the cost of waiting differs across customers based on their opportunity cost of time.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Time and money are not equally scarce for everyone", correct: true },
      { text: "All businesses charge exactly the same prices regardless of demand", errorType: "outside_knowledge_not_supported_by_passage", why: "Uniform pricing across businesses is not the reason the passage gives for the substitution's non-neutrality; differing scarcity of time is." },
      { text: "Restaurants always prefer wealthy customers over others", errorType: "outside_knowledge_not_supported_by_passage", why: "Restaurant preference for particular customers is not the mechanism the passage describes; differing personal opportunity costs of time is." },
      { text: "Waiting in line is illegal in some jurisdictions", errorType: "outside_knowledge_not_supported_by_passage", why: "Legal status of queuing is not discussed anywhere in the passage." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_queuing_economics",
    stem: "According to the passage, a wait that costs a wealthy customer little relative to their earnings can be:",
    reasoning: "The passage states such a wait 'can be prohibitively costly for someone whose time carries a higher opportunity cost relative to their income, or who simply cannot spare the hours at all.'",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Prohibitively costly for someone with a higher opportunity cost of time relative to income", correct: true },
      { text: "Equally costly for every customer regardless of income", errorType: "sign_or_direction_reversal", why: "The passage's entire point is that the same wait is NOT equally costly across customers with different circumstances." },
      { text: "Always cheaper for lower-income customers than for wealthy ones", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage suggests the opposite may often be true — that waiting can be relatively more costly for those with less flexible time, not automatically cheaper." },
      { text: "Completely unrelated to a person's financial circumstances", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage directly ties the cost of waiting to a person's financial and time circumstances, not treating them as unrelated." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_queuing_economics",
    stem: "Based on the passage's argument, a business that switches from a long waitlist to a significantly higher fixed price for immediate service would most likely be predicted to:",
    reasoning: "Since the passage argues queuing distributes cost via time (unevenly, based on opportunity cost) while pricing distributes cost via money, switching to a price-based system would shift the burden toward those with less money (even if they have more flexible time) and away from those with high-value time but less money, essentially changing which customers bear the access cost.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Shift the burden of access away from time-constrained, high-earning customers and toward customers with less money to spend", correct: true },
      { text: "Have absolutely no effect on which customers are able to access the good or service", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's entire argument is that the rationing method (time vs. money) systematically affects who bears the cost, so a switch would have a real, predictable distributional effect, not none at all." },
      { text: "Eliminate scarcity of the good or service entirely", errorType: "outside_knowledge_not_supported_by_passage", why: "Changing the method of rationing (time vs. price) doesn't eliminate underlying scarcity, which is a separate issue from how access is allocated." },
      { text: "Make the good or service available to literally everyone who wants it, at any price", errorType: "outside_knowledge_not_supported_by_passage", why: "A higher fixed price would still ration access, just via money rather than time, not eliminate rationing to make it available to absolutely everyone." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_queuing_economics",
    stem: "According to the passage, economists note an 'uncomfortable implication' that a business keeping prices low and allowing a line to form is:",
    reasoning: "The passage states this business 'is not avoiding rationing by price, as it might appear, but merely switching to a rationing currency, time, that happens to be distributed even more unevenly across customers than money is.'",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Not avoiding rationing, but switching to a rationing currency (time) distributed even more unevenly than money", correct: true },
      { text: "Successfully avoiding any form of rationing altogether", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states the business is 'not avoiding rationing,' contradicting this claim of successfully avoiding it." },
      { text: "Guaranteed to lose money compared to raising prices", errorType: "outside_knowledge_not_supported_by_passage", why: "Profitability comparison is not the 'uncomfortable implication' the passage discusses; the distributional unevenness of the rationing currency is." },
      { text: "Acting more fairly than a business that charges higher prices", errorType: "sign_or_direction_reversal", why: "The passage's 'uncomfortable implication' is precisely that this approach may be less, not more, fair, since time is even more unevenly distributed than money." },
    ],
  },

  // --- cars_expert_superstition (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_expert_superstition",
    stem: "According to the passage, professional athletes, surgeons, and traders are sometimes found to hold superstitious rituals despite:",
    reasoning: "The passage states this is despite these professionals 'possessing exactly the kind of statistical sophistication that should make such beliefs easy to dismiss.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Possessing the statistical sophistication that should make such beliefs easy to dismiss", correct: true },
      { text: "Never having any formal training in their profession", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage attributes statistical sophistication to these experts, the opposite of a lack of formal training." },
      { text: "Being explicitly required by their profession to hold such beliefs", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't describe any professional requirement to hold superstitious beliefs." },
      { text: "Having no genuine skill in their field at all", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage describes these as skilled experts, not individuals lacking genuine skill." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_expert_superstition",
    stem: "According to the passage, the more interesting explanation notes that high-stakes performance domains involve:",
    reasoning: "The passage states this explanation notes such domains 'involve genuine, irreducible uncertainty that skill cannot eliminate.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Genuine, irreducible uncertainty that skill cannot eliminate", correct: true },
      { text: "No uncertainty at all once sufficient skill is developed", errorType: "sign_or_direction_reversal", why: "The passage explicitly states uncertainty is irreducible even with skill, the opposite of uncertainty disappearing with sufficient skill." },
      { text: "A complete absence of any risk to the performer", errorType: "outside_knowledge_not_supported_by_passage", why: "High-stakes domains, by definition and by the passage's framing, involve real uncertainty and risk, not an absence of it." },
      { text: "Outcomes that are entirely predetermined regardless of performance", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't claim outcomes are predetermined; it describes genuine, irreducible uncertainty, which implies outcomes are not fixed in advance." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_expert_superstition",
    stem: "According to the passage, a ritual can reliably reduce a performer's anxiety and increase their sense of control, which:",
    reasoning: "The passage states this increased sense of control 'itself can measurably improve performance,' giving the ritual a real, if indirect, functional benefit.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Itself can measurably improve performance", correct: true },
      { text: "Has no measurable effect on performance whatsoever", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states this increased sense of control 'can measurably improve performance,' the opposite of having no effect." },
      { text: "Always causes performance to decline due to overconfidence", errorType: "sign_or_direction_reversal", why: "The passage describes this as improving, not declining, performance." },
      { text: "Only works for surgeons, not athletes or traders", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage applies this mechanism generally across the professions it mentions (athletes, surgeons, traders), not exclusively to surgeons." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_expert_superstition",
    stem: "Which finding would most directly support the passage's 'more interesting explanation' for expert superstition?",
    reasoning: "This explanation holds that a ritual's real mechanism is anxiety reduction and increased sense of control, not actual causal effect on outcomes; evidence that performing the ritual measurably reduces physiological stress markers and improves performance, even when the ritual has no plausible causal link to the outcome, would directly support this account.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Performers who follow their ritual show reduced physiological stress markers and improved performance, even though the ritual has no plausible causal link to the outcome", correct: true },
      { text: "Performers who follow their ritual report genuinely believing it directly causes good outcomes", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "This describes the performer's own mistaken belief, which the passage already assumes, rather than providing new evidence for the anxiety-reduction mechanism." },
      { text: "Rituals are more common among traders than among surgeons", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Relative frequency across professions doesn't test the specific anxiety-reduction/control mechanism the passage proposes." },
      { text: "Performers who abandon their rituals report feeling relieved and less superstitious", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Reported relief upon abandoning a ritual doesn't directly test whether the ritual worked via anxiety-reduction while it was still practiced." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_expert_superstition",
    stem: "According to the passage, under the more interesting explanation, the superstition is not really a false belief about causation, but:",
    reasoning: "The passage states it is instead 'a psychological tool whose real mechanism of action the performer has simply mislabeled.'",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "A psychological tool whose real mechanism of action the performer has mislabeled", correct: true },
      { text: "A completely accurate scientific description of a causal mechanism", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the performer's own causal explanation as mislabeled, not as an accurate scientific description." },
      { text: "Something with absolutely no real effect on the performer at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the ritual as having a real effect (via anxiety reduction), just not through the mechanism the performer believes." },
      { text: "A deliberate deception the performer knowingly practices on others", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage frames this as the performer's own genuine (if mistaken) belief, not a deliberate deception aimed at others." },
    ],
  },

  // --- cars_poetry_translation (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_poetry_translation",
    stem: "According to the passage, translating prose is usually treated as a problem of preserving:",
    reasoning: "The passage states prose translation 'is usually treated as a problem of preserving meaning and tone across languages, a difficult but bounded task.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Meaning and tone across languages", correct: true },
      { text: "The exact number of words in the original text", errorType: "outside_knowledge_not_supported_by_passage", why: "Word count preservation is not what the passage describes as the goal of prose translation." },
      { text: "The visual formatting of the original document", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Visual formatting is not discussed in the passage as the goal of prose translation." },
      { text: "The publisher's marketing strategy", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Marketing strategy is unrelated to the passage's discussion of translation's core challenge." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_poetry_translation",
    stem: "According to the passage, poetry translation is described as a categorically harder problem because a poem's meaning is often inseparable from:",
    reasoning: "The passage states this is because meaning is 'frequently inseparable from formal features — rhyme, meter, the specific sound of a particular word.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Formal features like rhyme, meter, and the specific sound of particular words", correct: true },
      { text: "The publisher's chosen font and page layout", errorType: "outside_knowledge_not_supported_by_passage", why: "Font and page layout are not the formal features the passage identifies; rhyme, meter, and sound are." },
      { text: "The poem's total length in number of lines", errorType: "outside_knowledge_not_supported_by_passage", why: "Line count is not identified in the passage as the source of poetry's translation difficulty." },
      { text: "The historical period in which the poem was written", errorType: "outside_knowledge_not_supported_by_passage", why: "Historical period is not the formal feature the passage identifies as inseparable from meaning in poetry." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_poetry_translation",
    stem: "According to the passage, a poetry translator faces a choice between preserving literal meaning, preserving sound, or:",
    reasoning: "The passage states the translator faces a choice among these options 'or attempt some negotiated compromise between the two that fully satisfies neither.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Attempting a negotiated compromise that fully satisfies neither goal", correct: true },
      { text: "Achieving both meaning and sound perfectly, with no tradeoff required", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly frames this as a forced choice with tradeoffs, not a situation where both can be perfectly achieved simultaneously." },
      { text: "Abandoning the translation project entirely as impossible in every case", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes translators making difficult choices and producing results, including compromises, not universally abandoning every project." },
      { text: "Consulting the original poet directly for their preference", errorType: "outside_knowledge_not_supported_by_passage", why: "Consulting the original poet is not one of the options the passage describes; many poems are also from authors no longer available to consult." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_poetry_translation",
    stem: "Based on the passage's argument, some translators conclude that a translated poem should more honestly be described as:",
    reasoning: "The passage states these translators conclude a poem 'cannot be translated at all, only rewritten as a new poem in the second language that stands in some acknowledged, imperfect relationship to the first.'",
    difficulty: 0.4,
    sirs: 3,
    options: [
      { text: "A new poem standing in an acknowledged, imperfect relationship to the original", correct: true },
      { text: "An exact, word-for-word equivalent of the original poem", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage explicitly argues against the possibility of an exact equivalent, given the inseparability of meaning and form in poetry." },
      { text: "A completely unrelated, independent work with no connection to the original", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes an 'acknowledged...relationship to the first,' meaning some connection remains, not complete independence." },
      { text: "A literal translation identical in status to an instruction manual's translation", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly argues this label is less honest than calling it a rewritten new poem, contrasting it with a straightforward technical translation like an instruction manual." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_poetry_translation",
    stem: "According to the passage, poetry translation forces a translator into choices that:",
    reasoning: "The passage states these are 'choices a prose translator rarely faces as starkly.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "A prose translator rarely faces as starkly", correct: true },
      { text: "Are completely identical to those faced by a prose translator", errorType: "sign_or_direction_reversal", why: "The passage explicitly distinguishes poetry translation's starker choices from those a prose translator faces, not equating them." },
      { text: "Only apply to translations between closely related languages", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't restrict this difficulty to closely related language pairs; it describes a general challenge of poetry translation." },
      { text: "Have already been fully solved by modern translation software", errorType: "outside_knowledge_not_supported_by_passage", why: "Translation software is not discussed anywhere in the passage." },
    ],
  },

  // --- cars_algorithmic_curation_ethics (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_algorithmic_curation_ethics",
    stem: "According to the passage, a newspaper's front-page editor makes choices that are:",
    reasoning: "The passage states these are 'visible, accountable choices...choices readers can evaluate and criticize because the editor and their reasoning are, at least in principle, identifiable.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Visible and accountable, made by an identifiable person", correct: true },
      { text: "Completely hidden and impossible for anyone to identify", errorType: "sign_or_direction_reversal", why: "The passage explicitly describes editorial choices as visible and identifiable, the opposite of hidden." },
      { text: "Made collectively by an anonymous algorithm", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage attributes algorithmic, anonymous decision-making to social media feeds, not to the newspaper editor being described here." },
      { text: "Entirely random with no identifiable reasoning behind them", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the editor's choices as reflecting identifiable reasoning, not randomness." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_algorithmic_curation_ethics",
    stem: "According to the passage, a social media feed's ranking algorithm makes comparably consequential choices, but:",
    reasoning: "The passage states this occurs 'without any individual editor to hold accountable and often without the platform itself fully able to explain why a particular piece of content was promoted or suppressed.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Without any individual editor to hold accountable, and often without a clear explanation available", correct: true },
      { text: "With even greater transparency than a newspaper editor provides", errorType: "sign_or_direction_reversal", why: "The passage explicitly frames the algorithm's decision-making as opaque, the opposite of greater transparency." },
      { text: "Only affecting a small, negligible number of readers", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage frames these algorithmic choices as 'comparably consequential' to editorial choices, not negligible in scale." },
      { text: "Exactly identically to how a print editor makes decisions", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly contrasts the algorithm's opacity with the editor's identifiable accountability, not equating the two processes." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_algorithmic_curation_ethics",
    stem: "According to the passage, critics argue this opacity represents:",
    reasoning: "The passage states critics argue this is 'not a minor technical inconvenience but an erosion of a specific kind of accountability that print editorial judgment, whatever its flaws, always provided.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "An erosion of a specific kind of accountability print editorial judgment always provided", correct: true },
      { text: "A minor, inconsequential technical inconvenience", errorType: "sign_or_direction_reversal", why: "The passage explicitly states critics view this as more than 'a minor technical inconvenience,' the opposite framing." },
      { text: "An improvement over the accountability of traditional print editors", errorType: "sign_or_direction_reversal", why: "The passage frames this as an erosion (a loss), not an improvement, of accountability." },
      { text: "A problem that has already been fully solved by current platforms", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage presents this as an ongoing, unresolved critique, not a problem already solved." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_algorithmic_curation_ethics",
    stem: "Based on the passage's argument, which policy change would most directly address the specific accountability concern the passage raises?",
    reasoning: "The passage's concern is the absence of an identifiable party who can explain and defend content-ranking decisions in the way an editor could; a policy requiring platforms to provide specific, individually-defensible explanations for promoting or suppressing particular content would directly restore the kind of accountability the passage says algorithmic curation currently lacks.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Requiring platforms to provide specific, defensible explanations for why particular content was promoted or suppressed", correct: true },
      { text: "Requiring platforms to increase the total amount of content shown to each user", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Increasing content volume doesn't address the specific concern about accountability and explainability of ranking decisions." },
      { text: "Requiring platforms to charge a subscription fee for access", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "A subscription fee is unrelated to the accountability and explainability concern the passage raises about algorithmic curation." },
      { text: "Requiring platforms to remove all algorithmic ranking and show content in a purely random order", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "While this would remove the ranking decision entirely, it doesn't address the passage's specific concern about restoring accountable, defensible editorial judgment; it simply eliminates curation altogether." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_algorithmic_curation_ethics",
    stem: "According to the passage, the specific kind of accountability being eroded is the ability to:",
    reasoning: "The passage states this is 'the ability to ask a responsible party why this and not that, and to receive an answer in terms of a judgment someone is willing to defend.'",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "Ask a responsible party why a choice was made and receive a defensible answer", correct: true },
      { text: "Access content for free without any subscription cost", errorType: "outside_knowledge_not_supported_by_passage", why: "Free access/cost is not the accountability concept the passage discusses; the ability to question a responsible party is." },
      { text: "View an unlimited amount of content on the platform", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Content volume is unrelated to the specific accountability concern the passage identifies about explainable, defensible decision-making." },
      { text: "Personally control every aspect of the platform's algorithm", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Direct personal control over the algorithm is not what the passage describes as the eroded form of accountability; the ability to question and receive a defensible answer from a responsible party is." },
    ],
  },
];
