import type { ItemDef } from "./types";

export const itemsCars3: ItemDef[] = [
  // --- cars_tyranny_of_clock (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_tyranny_of_clock",
    stem: "According to the passage, before mechanical clocks became widespread, most people organized their days around:",
    reasoning: "The passage states people organized their days 'around events...rather than around a uniform, abstract measure of elapsed time.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Events, such as sunrise or the completion of a task", correct: true },
      { text: "A uniform, abstract measure of elapsed time", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly contrasts event-based organization with this abstract, clock-based measure, which came later." },
      { text: "Written schedules distributed by local governments", errorType: "outside_knowledge_not_supported_by_passage", why: "Written government schedules are not discussed in the passage's account of pre-clock timekeeping." },
      { text: "The exact hour announced by early clock towers", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage describes a time before mechanical clocks were widespread, which would exclude relying on clock tower announcements." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_tyranny_of_clock",
    stem: "According to the passage, critics argue that clock time did not simply measure labor more accurately but:",
    reasoning: "The passage states critics argue clock time 'actively reorganized what counted as labor in the first place.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Actively reorganized what counted as labor in the first place", correct: true },
      { text: "Made factory work entirely obsolete", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses the clock's role in factory discipline, not making factory work obsolete." },
      { text: "Had no real effect on how work was organized at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly credits clock time with a significant reorganizing effect on the concept of labor." },
      { text: "Simply confirmed what workers had always believed about time", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames clock time as introducing something new (a concept of measurable wasted time), not merely confirming prior beliefs." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_tyranny_of_clock",
    stem: "The passage argues that a task-based day has no natural concept of 'wasted time' between tasks because:",
    reasoning: "The passage's logic is that 'wasted time' as a concept requires a uniform, countable measure against which a gap can be judged empty or unproductive; a task-based day, lacking that uniform measure, has no baseline against which any interval could register as 'wasted.'",
    difficulty: 0.5,
    sirs: 2,
    options: [
      { text: "Without a uniform, countable time measure, there is no baseline against which a gap could register as wasted", correct: true },
      { text: "People in a task-based system never took any breaks at all", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's argument concerns the absence of a measurable concept of waste, not a claim that no breaks or gaps ever occurred." },
      { text: "Task-based systems were always more efficient than clock-based ones", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't compare overall efficiency between the two systems; it discusses how each system conceptualizes time differently." },
      { text: "Clocks did not exist in any form before the factory era", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses the spread and disciplinary use of factory clocks, not a claim that clocks in any form never existed earlier." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_tyranny_of_clock",
    stem: "Which finding would most directly support the passage's argument about clock time reorganizing the concept of labor?",
    reasoning: "The passage's argument is that clock time introduced a new concept of 'wasted' time that didn't exist under task-based organization; evidence that workers were specifically disciplined or penalized for idle clock-measured minutes (something that would have been meaningless under a task-based system) would directly support this.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Historical factory records show workers being penalized specifically for minutes of idle time between tasks, a practice absent in earlier task-based work", correct: true },
      { text: "Historical records show factory workers were paid more than pre-industrial task-based workers", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "Pay differences don't specifically address the passage's claim about the clock introducing a new concept of measurable wasted time." },
      { text: "Historical records show clocks became more accurate over the centuries", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Improved clock accuracy doesn't address the passage's specific claim about the concept of 'wasted time' being newly created." },
      { text: "Historical records show task-based workers also used sundials occasionally", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "Occasional sundial use doesn't address whether a countable concept of wasted time existed under task-based organization." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_tyranny_of_clock",
    stem: "According to the passage, the spread of the factory clock is often credited with introducing:",
    reasoning: "The passage states the factory clock is 'often credited with introducing a new discipline: workers were now paid, scheduled, and disciplined according to a clock's indifferent ticking.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "A new discipline based on the clock's indifferent ticking", correct: true },
      { text: "A reduction in the total number of hours worked per week", errorType: "outside_knowledge_not_supported_by_passage", why: "Working hours are not discussed in the passage; the focus is on the introduction of clock-based discipline." },
      { text: "The complete elimination of factory work altogether", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage describes the clock transforming, not eliminating, factory work." },
      { text: "A return to task-based scheduling in factories", errorType: "sign_or_direction_reversal", why: "The passage describes the clock replacing, not returning to, task-based scheduling." },
    ],
  },

  // --- cars_rosy_retrospection (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_rosy_retrospection",
    stem: "According to the passage, people asked to recall a difficult period often rate it, in retrospect, as:",
    reasoning: "The passage states people 'often rate the experience, in retrospect, as more positive than the moment-by-moment reports they gave while actually living through it.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "More positive than their moment-by-moment reports at the time", correct: true },
      { text: "Exactly as negative as their moment-by-moment reports at the time", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly describes a shift toward more positive retrospective ratings, not an exact match to in-the-moment reports." },
      { text: "More negative than their moment-by-moment reports at the time", errorType: "sign_or_direction_reversal", why: "Reverses the direction of the shift the passage describes." },
      { text: "Impossible to recall at all after enough time has passed", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes people successfully recalling and rating the experience, just with a systematic positive shift, not an inability to recall it." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_rosy_retrospection",
    stem: "The passage's 'less flattering-to-the-rememberer' explanation attributes rosy retrospection to memory being:",
    reasoning: "The passage states this explanation holds memory 'is not an average of every moment but a reconstruction weighted heavily toward the ending and toward a few salient peaks, largely discarding the tedious middle.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "A reconstruction weighted toward the ending and salient peaks, discarding the tedious middle", correct: true },
      { text: "An exact, unweighted average of every single moment experienced", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states memory is 'not an average of every moment,' the opposite of this claim." },
      { text: "A deliberate, conscious lie the rememberer tells to impress others", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage attributes this to the second, 'less flattering' explanation as a structural memory phenomenon, not deliberate deception." },
      { text: "Completely random and unrelated to the actual timing of events", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes a specific, systematic weighting pattern (toward endings and peaks), not randomness." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_rosy_retrospection",
    stem: "The passage contrasts two explanations for rosy retrospection. The key difference between them is that the first explanation treats the phenomenon as:",
    reasoning: "The passage frames the first explanation as 'motivated forgetting, a self-serving edit,' implying intentional or motivated distortion, whereas the second frames it as a structural byproduct of how memory naturally summarizes experience — not motivated at all.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "A motivated, self-serving edit, while the second treats it as a structural feature of how memory works", correct: true },
      { text: "A structural feature of memory, while the second treats it as motivated self-flattery", errorType: "sign_or_direction_reversal", why: "Reverses which explanation the passage assigns to motivation versus structure." },
      { text: "Entirely accurate, while the second treats it as entirely inaccurate", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage doesn't frame either explanation as claiming the memory is fully accurate; both describe some form of systematic shift from the moment-by-moment experience." },
      { text: "Impossible to test empirically, while the second is easily testable", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't discuss the relative testability of the two explanations." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_rosy_retrospection",
    stem: "Which finding would most directly support the passage's 'less flattering' structural explanation over the motivated-forgetting explanation?",
    reasoning: "If rosy retrospection occurred even in situations with no self-serving motive to distort memory — for instance, recalling a stranger's experience rather than one's own — this would suggest the effect stems from a general structural feature of how memory is reconstructed rather than from self-serving motivation, which requires a personal stake to operate.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "People show the same positively-shifted recall pattern even when reporting on a stranger's experience, with no personal stake involved", correct: true },
      { text: "People who are told in advance to remember accurately still show some positive shift", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "This doesn't specifically distinguish a self-serving motive from a structural memory account, since motivated distortion could persist despite explicit accuracy instructions too." },
      { text: "People report feeling happier immediately after a difficult experience ends", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "Immediate post-experience mood doesn't address the specific retrospective memory-reconstruction question the passage raises." },
      { text: "People with better memory overall show less rosy retrospection", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "General memory ability doesn't specifically test whether the effect is self-serving/motivated versus a structural reconstruction process." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_rosy_retrospection",
    stem: "According to the passage, if the structural (reconstruction) account is correct, 'misremembering' the past as better than it felt is:",
    reasoning: "The passage states that under this account, the phenomenon 'is not really a distortion introduced after the fact, but a direct consequence of how experience gets summarized into memory in the first place.'",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "A direct consequence of how experience gets summarized into memory, not a later distortion", correct: true },
      { text: "A deliberate distortion consciously introduced well after the experience ends", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states this account frames it as not a distortion introduced after the fact." },
      { text: "Evidence that memory research is fundamentally flawed", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't use this phenomenon to critique memory research methodology broadly." },
      { text: "Something that only happens to people with memory disorders", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses this as a general phenomenon in ordinary memory, not one limited to clinical memory disorders." },
    ],
  },

  // --- cars_norman_doors (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_norman_doors",
    stem: "According to the passage, when a door with a flat plate handle must be pulled, people will reliably:",
    reasoning: "The passage states such a door 'will reliably cause people to push it first' because the flat plate visually suggests pushing.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Push it first, since the flat plate suggests pushing", correct: true },
      { text: "Immediately identify the correct pulling motion", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly describes people reliably making the pushing mistake, not immediately identifying the correct action." },
      { text: "Refuse to interact with the door at all", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage describes people attempting to push the door, not refusing to interact with it." },
      { text: "Read an instructional label before attempting to open it", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's whole point is that a well-designed object shouldn't require a label at all; it doesn't describe people reading one here." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_norman_doors",
    stem: "According to the passage, when a door's design suggests the wrong action, whose fault is this considered to be?",
    reasoning: "The passage explicitly states 'the mistake is not the fault of the person pushing' — placing responsibility on the design itself, per the concept of affordance.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "The design's fault, not the person's", correct: true },
      { text: "The person's fault, for not reading instructions carefully", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states the mistake is 'not the fault of the person pushing.'" },
      { text: "No one's fault; such mistakes are considered unavoidable and meaningless", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage clearly assigns responsibility to the design, not treating the mistake as meaningless or unassignable." },
      { text: "The building's architect exclusively, regardless of who designed the door itself", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses design responsibility generally (the door's affordance), not a specific distinction between architect and door designer." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_norman_doors",
    stem: "According to the passage, a well-designed interface or tool requires no manual because:",
    reasoning: "The passage states 'its correct use is legible from its shape and arrangement alone' — the design itself communicates proper use without needing separate instructions.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Its correct use is legible from its shape and arrangement alone", correct: true },
      { text: "It has been extensively tested by professional engineers", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "The passage attributes manual-free usability to visible affordance, not to a claim about the amount of engineering testing performed." },
      { text: "It is simpler in overall function than a poorly designed one", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's point is about visible legibility of use, not about overall functional simplicity." },
      { text: "Users are specifically trained in advance to use it correctly", correct: false, errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's entire point is that good design requires no manual or prior training at all — legibility comes from the design itself." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_norman_doors",
    stem: "Based on the passage's argument, a company response to persistent user errors with a product that would most directly reflect the passage's underlying philosophy would be to:",
    reasoning: "Since the passage argues design failures, not user failures, cause these errors, and that no amount of training fixes a bad affordance, the philosophy implies the company should redesign the product's visible cues rather than blame or retrain users.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Redesign the product's visible cues so correct use becomes obvious without instruction", correct: true },
      { text: "Add a longer instruction manual explaining the correct usage in detail", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage explicitly argues good design requires no manual at all; adding more instructions doesn't fix an affordance problem." },
      { text: "Blame users for not being attentive enough when using the product", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage explicitly states such errors are not the fault of the user, contradicting a user-blaming response." },
      { text: "Require mandatory training sessions before customers can use the product", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage states a well-designed product 'requires no manual,' implying training is a workaround for bad design, not the recommended fix." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_norman_doors",
    stem: "According to the passage, a poorly designed system that suggests the wrong action will keep producing the same 'human error':",
    reasoning: "The passage states such a system will keep producing this error 'indefinitely, no matter how many people encounter it' — a persistent, predictable design flaw, not a one-off user mistake.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Indefinitely, no matter how many people encounter it", correct: true },
      { text: "Only for the very first user who ever encounters it", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states this error recurs indefinitely across many users, not just the first one." },
      { text: "Less and less often as more people become familiar with it", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the error persisting indefinitely regardless of how many people encounter it, not fading with familiarity." },
      { text: "Only in laboratory testing conditions, never in real-world use", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage describes this as a general, real-world design phenomenon, not one confined to laboratory settings." },
    ],
  },

  // --- cars_currency_representation (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_currency_representation",
    stem: "According to the passage, modern fiat currency makes the intrinsic-value assumption difficult to sustain because:",
    reasoning: "The passage states this is because 'a banknote's material cost is negligible and no metal backs its value' — there is no intrinsic physical property accounting for the currency's worth.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "A banknote's material cost is negligible and no metal backs its value", correct: true },
      { text: "Fiat currency is illegal in most modern countries", errorType: "outside_knowledge_not_supported_by_passage", why: "Legality of fiat currency is not discussed in the passage; the issue is about the basis of its value." },
      { text: "Fiat currency can only be used within a single country's borders", errorType: "outside_knowledge_not_supported_by_passage", why: "Cross-border usability is not the issue the passage raises about intrinsic value." },
      { text: "Banknotes are more expensive to produce than the value they represent", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage states the opposite — material cost is negligible relative to face value — not that production is more expensive." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_currency_representation",
    stem: "According to the passage's 'more accurate account,' a currency's value is best described as:",
    reasoning: "The passage states this account treats currency's value 'as entirely relational' — valuable to the extent a community confidently expects others to accept it in exchange.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Entirely relational, depending on collective confidence that others will accept it", correct: true },
      { text: "Fixed permanently by the amount of metal it once represented historically", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's account explicitly moves away from metal-backing as the basis of value, toward collective confidence instead." },
      { text: "Determined solely by the government's military strength", errorType: "outside_knowledge_not_supported_by_passage", why: "Military strength is not a factor the passage's account of currency value discusses." },
      { text: "Entirely arbitrary and unrelated to any social factor", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's account ties value directly to a specific social factor — collective confidence — not to arbitrary, unrelated causes." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_currency_representation",
    stem: "The passage states that a currency's relational value 'evaporates rapidly once that expectation breaks down, as in a hyperinflationary collapse.' This example is used to illustrate that:",
    reasoning: "This example illustrates the practical consequence of the passage's relational account: since currency value depends entirely on ongoing collective confidence, a collapse in that confidence (as in hyperinflation) causes value to disappear rapidly, demonstrating there is no separate intrinsic backstop holding value in place.",
    difficulty: 0.5,
    sirs: 2,
    options: [
      { text: "Currency value has no separate, intrinsic backstop beyond collective confidence itself", correct: true },
      { text: "Hyperinflation always occurs eventually in every currency system", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage uses hyperinflation as an illustrative example of confidence collapse, not as a claim that it always eventually happens." },
      { text: "Metal-backed currencies never experience any form of collapse", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't compare the collapse resistance of metal-backed versus fiat currencies." },
      { text: "Governments always cause hyperinflation deliberately", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't attribute deliberate intent to governments regarding hyperinflation; it uses the phenomenon to illustrate the relational nature of value." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_currency_representation",
    stem: "Which observation would most directly support the passage's relational account of currency value?",
    reasoning: "The relational account predicts that a currency's value should track collective confidence rather than any physical backing; observing that a currency's value drops sharply the moment public confidence collapses, even though its physical form is completely unchanged, would directly support this account.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "A currency's market value collapses suddenly after a loss of public confidence, even though the physical banknotes themselves are unchanged", correct: true },
      { text: "A currency's banknotes are printed on higher-quality paper than in previous decades", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "Paper quality is a physical property unrelated to testing whether value tracks collective confidence rather than intrinsic material properties." },
      { text: "A government mints new coins using a cheaper metal alloy", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "A change in metal alloy doesn't directly test whether the currency's value depends on collective confidence versus intrinsic material value." },
      { text: "Two different countries use the same paper supplier for their currency", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Shared paper suppliers have no bearing on the relational-confidence account of currency value the passage proposes." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_currency_representation",
    stem: "According to the passage, asking 'what backs the currency' independently of collective confidence is described as:",
    reasoning: "The passage states this question is 'close to a category error — the confidence is not a precondition for the currency's value, it is the value.'",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "Close to a category error, since confidence itself is the value, not merely a precondition for it", correct: true },
      { text: "The single most important economic question to answer", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage treats this question as a conceptual mistake (a category error), not as the most important economic question." },
      { text: "A question with a simple, universally agreed factual answer", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames the question as based on a flawed premise, not as having a simple, settled factual answer." },
      { text: "A question only relevant to historical, metal-backed currencies", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses this question in relation to modern fiat currency specifically, not historical metal-backed currency." },
    ],
  },

  // --- cars_eavesdropping_ethics (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_eavesdropping_ethics",
    stem: "According to the passage, deliberately eavesdropping is widely considered:",
    reasoning: "The passage states deliberate eavesdropping 'is widely considered a clear ethical violation.'",
    difficulty: 0.1,
    sirs: 1,
    options: [
      { text: "A clear ethical violation", correct: true },
      { text: "Completely ethically neutral", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly describes deliberate eavesdropping as a clear ethical violation, not neutral." },
      { text: "More ethical than merely overhearing a conversation", errorType: "sign_or_direction_reversal", why: "The passage treats deliberate eavesdropping as more clearly wrong, while merely overhearing is treated as more ambiguous, the reverse of this claim." },
      { text: "Illegal in every jurisdiction without exception", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses the ethics, not the specific legal status across every jurisdiction, of eavesdropping." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_eavesdropping_ethics",
    stem: "According to the passage, the intention-based account holds that overhearing a conversation is ethically acceptable because:",
    reasoning: "The passage states this account holds 'no wrong has been committed regardless of what they now know,' since 'the overhearer did nothing to bring the information to themselves.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "The overhearer did nothing to bring the information to themselves", correct: true },
      { text: "The information overheard is always trivial and unimportant", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's intention-based account is about the overhearer's lack of active effort, not about the triviality of the information." },
      { text: "Overhearing is technically illegal but rarely enforced", errorType: "outside_knowledge_not_supported_by_passage", why: "Legal enforcement is not discussed in the passage's account of the ethics of overhearing." },
      { text: "The people having the conversation consented to being overheard", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses overhearing a private conversation, implying no consent was given; the intention-based account rests on the overhearer's lack of intent, not the speakers' consent." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_eavesdropping_ethics",
    stem: "According to the passage, the competing account argues that once information has been overheard, further ethical obligations attach to:",
    reasoning: "The passage states these obligations attach to 'what the listener does next — repeating it, acting on it, or pretending not to have heard it.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "What the listener does next with the information", correct: true },
      { text: "Whatever the original speakers intended to communicate", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's competing account focuses on the listener's subsequent actions, not on reinterpreting the original speakers' intentions." },
      { text: "The volume at which the original conversation was held", errorType: "outside_knowledge_not_supported_by_passage", why: "Volume of the original conversation is not discussed as the basis for further ethical obligations in the passage." },
      { text: "Whether the information was true or false", errorType: "outside_knowledge_not_supported_by_passage", why: "Truth or falsity of the overheard information is not the factor the passage's competing account identifies as generating further obligations." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_eavesdropping_ethics",
    stem: "Based on the passage, which scenario would the competing (obligations-based) account treat as ethically significant in a way the pure intention-based account would not?",
    reasoning: "The competing account holds that ethical obligations attach to what a listener does after overhearing something, regardless of the innocence of the overhearing itself; a scenario where someone innocently overhears something and then deliberately spreads it to cause harm would be judged significant under the competing account (due to the harmful subsequent action) but potentially excused entirely under a pure intention-based account focused only on the innocence of the initial overhearing.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "A person who innocently overhears private information and then deliberately spreads it to cause harm", correct: true },
      { text: "A person who deliberately presses their ear to a door to listen in on a conversation", errorType: "outside_knowledge_not_supported_by_passage", why: "This is a case of deliberate eavesdropping, which both accounts (and the passage generally) already treat as a clear ethical violation, not a case distinguishing the two accounts." },
      { text: "A person who overhears nothing at all during an entire conversation", errorType: "outside_knowledge_not_supported_by_passage", why: "With no information overheard, there is nothing for either account to evaluate ethically." },
      { text: "A person who is explicitly invited to listen to a conversation", errorType: "outside_knowledge_not_supported_by_passage", why: "Being invited removes the 'overhearing' framing entirely, since consent was given, unlike the innocent-overhearing scenario the passage discusses." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_eavesdropping_ethics",
    stem: "According to the passage, the informational outcome for a listener can be identical whether they:",
    reasoning: "The passage states 'the informational outcome for the listener can be identical' whether they deliberately eavesdropped or merely overheard innocently — the same facts end up known either way.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Deliberately eavesdropped or merely overheard innocently", correct: true },
      { text: "Speak loudly or speak quietly", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's comparison concerns deliberate eavesdropping versus innocent overhearing, not the volume of speech." },
      { text: "Are a stranger or a close friend of the speakers", errorType: "outside_knowledge_not_supported_by_passage", why: "Relationship to the speakers is not the comparison the passage draws; the intentionality of listening is." },
      { text: "Understand the language being spoken or do not understand it", errorType: "outside_knowledge_not_supported_by_passage", why: "Language comprehension is not the variable the passage discusses; the comparison is about the manner of coming to overhear the conversation." },
    ],
  },

  // --- cars_street_naming (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_street_naming",
    stem: "According to the passage, disputes over renaming a street are rarely about navigation because:",
    reasoning: "The passage states this is because 'any name would serve equally well for wayfinding' — navigation doesn't actually depend on which specific name is chosen.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Any name would serve equally well for wayfinding purposes", correct: true },
      { text: "GPS technology has made street names entirely obsolete", errorType: "outside_knowledge_not_supported_by_passage", why: "GPS technology is not discussed in the passage as the reason navigation isn't the real issue in renaming disputes." },
      { text: "Most streets have no name at all", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses naming and renaming streets, implying they do have names; the point is about what's really being contested, not an absence of names." },
      { text: "City governments refuse to consider navigation in their decisions", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's point is that navigation is functionally irrelevant to the dispute (any name works), not that officials refuse to consider it." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_street_naming",
    stem: "According to the passage, what is actually being contested in disputes over renaming streets?",
    reasoning: "The passage states what's contested is 'whose history the everyday, unremarkable act of giving directions will quietly repeat, thousands of times a day.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Whose history gets quietly repeated through the everyday act of giving directions", correct: true },
      { text: "Which name is grammatically correct in the local language", errorType: "outside_knowledge_not_supported_by_passage", why: "Grammatical correctness is not the issue the passage identifies as being contested in these disputes." },
      { text: "The cost of replacing street signs throughout the city", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage frames the dispute as being about historical commemoration, not the practical cost of sign replacement." },
      { text: "Whether the street should be widened or narrowed", errorType: "outside_knowledge_not_supported_by_passage", why: "Street width is an unrelated urban-planning topic, not what the passage identifies as the substance of naming disputes." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_street_naming",
    stem: "The passage compares a street name to 'a very slow, very durable form of public commemoration' rather than a simple label, because most residents:",
    reasoning: "The passage states most residents 'may never consciously register the name's origin at all,' yet encounter and repeat it constantly — making it a commemoration that operates quietly and durably, below conscious notice, unlike a deliberately viewed monument.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Encounter the name constantly but rarely consciously register its historical origin", correct: true },
      { text: "Actively study the history behind every street name they use", errorType: "sign_or_direction_reversal", why: "The passage explicitly states residents rarely consciously register the origin, the opposite of actively studying it." },
      { text: "Vote directly on every proposed street name before it is adopted", errorType: "outside_knowledge_not_supported_by_passage", why: "Direct voting on street names is not discussed as the mechanism explaining why the passage calls this a 'slow, durable' commemoration." },
      { text: "Forget the street's name entirely within a few years", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the name being repeated 'thousands of times a day,' implying it is remembered and used constantly, not forgotten." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_street_naming",
    stem: "Which finding would most directly challenge the passage's central argument about what street-naming disputes are really about?",
    reasoning: "The passage argues these disputes are fundamentally about whose history is commemorated, not about practical navigation; a finding that disputes consistently arise purely over navigational confusion (e.g., duplicate names causing real wayfinding problems), with no connection to whose history is honored, would challenge the passage's framing.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Most heated street-renaming disputes occur over purely practical navigational confusion, with no connection to whose history is honored", correct: true },
      { text: "Most heated street-renaming disputes involve disagreement about whose historical legacy deserves commemoration", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "This is consistent with, not a challenge to, the passage's central argument about what these disputes are really about." },
      { text: "Cities have increased the budget allocated to street sign maintenance", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Sign maintenance budgets don't address whether disputes are fundamentally about historical commemoration or navigation." },
      { text: "Older streets tend to have shorter names than newer streets", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Name length has no bearing on whether renaming disputes are about commemoration versus navigation." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_street_naming",
    stem: "According to the passage, street names are 'often treated as' simple labels, chosen:",
    reasoning: "The passage opens by describing this common view: street names 'chosen for navigation and otherwise arbitrary.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "For navigation and otherwise arbitrary", correct: true },
      { text: "Specifically to honor a single historical figure in every case", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the common, simple view as treating names as arbitrary labels, not as deliberate acts of historical honor." },
      { text: "By a national government committee in every country", errorType: "outside_knowledge_not_supported_by_passage", why: "A specific naming authority process is not part of the common view the passage describes at the outset." },
      { text: "To reflect the personal preferences of local business owners", errorType: "outside_knowledge_not_supported_by_passage", why: "Business owner preference is not the common assumption about street naming the passage describes." },
    ],
  },

  // --- cars_true_crime_appeal (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_true_crime_appeal",
    stem: "According to the passage, the popularity of true crime is often explained as:",
    reasoning: "The passage states the popularity 'is often explained as simple morbid curiosity.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Simple morbid curiosity", correct: true },
      { text: "A carefully researched educational tool for law enforcement", errorType: "outside_knowledge_not_supported_by_passage", why: "Educational value for law enforcement is not the common explanation the passage attributes to true crime's popularity." },
      { text: "A recent phenomenon with no historical precedent", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage does not make a historical-novelty claim about true crime's popularity." },
      { text: "Something audiences uniformly dislike but watch anyway", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage discusses true crime's popularity and appeal, not a claim that audiences dislike it." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_true_crime_appeal",
    stem: "According to the passage, the morbid-curiosity explanation struggles to account for which structural feature of the genre?",
    reasoning: "The passage states true crime stories are 'disproportionately told from the perspective of the investigator working toward a solution, rather than from the perspective of the victim or the crime itself' — a pattern the simple morbid-curiosity explanation doesn't predict or explain well.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Stories are disproportionately told from the investigator's perspective, not the victim's or the crime's", correct: true },
      { text: "Stories always end with the criminal being caught", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage discusses unsolved cases being less popular, implying not all stories end with capture — the key structural feature is narrative perspective, not universal resolution." },
      { text: "Stories are told exclusively in documentary film format", errorType: "outside_knowledge_not_supported_by_passage", why: "Format (documentary vs. other media) is not the structural feature the passage identifies as challenging to the morbid-curiosity account." },
      { text: "Stories never include any violent content at all", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't claim true crime avoids violent content; it discusses the narrative's investigative framing as the key structural feature." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_true_crime_appeal",
    stem: "According to the passage, the investigator-focused narrative structure suggests the genre's core appeal is closer to that of:",
    reasoning: "The passage states 'true crime's core promise is closer to that of a puzzle or a procedural drama than to horror.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "A puzzle or procedural drama", correct: true },
      { text: "A horror film focused purely on fear", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states the appeal is closer to a puzzle/procedural, not to horror." },
      { text: "A romantic comedy", errorType: "outside_knowledge_not_supported_by_passage", why: "Romantic comedy is not a genre comparison the passage makes." },
      { text: "A live sporting event", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage compares true crime to puzzles and procedural dramas, not live sports." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_true_crime_appeal",
    stem: "According to the passage's argument, why are unsolved cases typically less commercially popular than solved ones, even when equally dramatic?",
    reasoning: "The passage explains this by its core claim that the genre's appeal lies in a chaotic event being rendered comprehensible and controlled through reasoning; an unsolved case cannot deliver this resolution-through-reasoning payoff, regardless of how dramatic the underlying events are, so it fails to satisfy the genre's central appeal.",
    difficulty: 0.5,
    sirs: 3,
    options: [
      { text: "Unsolved cases cannot deliver the resolution-through-reasoning payoff that the passage identifies as the genre's core appeal", correct: true },
      { text: "Unsolved cases are always less dramatic than solved ones", errorType: "outside_knowledge_not_supported_by_passage", why: "The question explicitly specifies cases that are 'equally dramatic,' ruling out drama level as the explanation." },
      { text: "Audiences are legally prohibited from viewing content about unsolved cases", errorType: "outside_knowledge_not_supported_by_passage", why: "No legal prohibition is discussed anywhere in the passage." },
      { text: "Unsolved cases always involve less violence than solved ones", errorType: "outside_knowledge_not_supported_by_passage", why: "Violence level is not the factor the passage's argument turns on; the resolution/comprehensibility payoff is." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_true_crime_appeal",
    stem: "According to the passage, what does true crime storytelling most reliably offer its audience?",
    reasoning: "The passage states the genre 'most reliably offers is not exposure to violence but the satisfaction of a chaotic, frightening event being rendered comprehensible and ultimately controlled through careful reasoning.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "The satisfaction of a chaotic event being rendered comprehensible through careful reasoning", correct: true },
      { text: "Direct exposure to graphic violence as the primary draw", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states the genre's reliable offering is 'not exposure to violence,' the opposite of this claim." },
      { text: "A guarantee that justice will always be served in every case", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't claim the genre guarantees justice; it discusses the comprehensibility/control payoff of reasoning through a case." },
      { text: "An opportunity to learn forensic science in technical detail", errorType: "outside_knowledge_not_supported_by_passage", why: "Technical forensic education is not what the passage identifies as the genre's core, reliable appeal." },
    ],
  },

  // --- cars_improvisation_illusion (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_improvisation_illusion",
    stem: "According to the passage, skilled improvisational performers are often praised for spontaneity, as though their work:",
    reasoning: "The passage states such performers are praised for spontaneity, 'as though their work emerges from nothing in the moment of performance.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Emerges from nothing in the moment of performance", correct: true },
      { text: "Is entirely scripted well in advance", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the common perception as spontaneous creation from nothing, not as fully scripted performance." },
      { text: "Requires no prior training of any kind", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage doesn't attribute this specific claim (no training required) to the common perception being described." },
      { text: "Is performed identically in every single show", errorType: "outside_knowledge_not_supported_by_passage", why: "Identical repetition across shows is not the perception the passage describes; the common view is about spontaneous, in-the-moment creation." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_improvisation_illusion",
    stem: "According to the passage, performers themselves describe improvisation as being built from:",
    reasoning: "The passage states performers describe it as built 'from a large repertoire of previously rehearsed patterns, phrases, and structures, recombined quickly enough that the recombination itself is what feels improvised.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "A large repertoire of previously rehearsed patterns, recombined quickly", correct: true },
      { text: "Entirely unplanned inspiration with no prior rehearsal at all", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly attributes improvisation to prior rehearsal of components, not to a complete absence of preparation." },
      { text: "A single, fixed script memorized word for word", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes flexible recombination of prepared components, not a single fixed, memorized script." },
      { text: "Random audience suggestions with no performer input at all", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage attributes improvisation's construction to the performer's own prepared repertoire, not to audience suggestions." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_improvisation_illusion",
    stem: "According to the passage, what audiences experience as spontaneity is best described as:",
    reasoning: "The passage states 'what audiences experience as spontaneity is not the absence of preparation but its successful concealment.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "The successful concealment of preparation, not its absence", correct: true },
      { text: "A completely accurate perception of a total absence of preparation", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states this perceived absence of preparation is not accurate — preparation is present but concealed." },
      { text: "Evidence that improvisation is a fundamentally dishonest art form", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't frame this concealment as dishonest; it presents it as the mechanism by which skilled improvisation actually works." },
      { text: "Something that only occurs in amateur, not professional, performances", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses skilled improvisational performers generally, not a distinction specific to amateur versus professional status." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_improvisation_illusion",
    stem: "Based on the passage's argument, which finding would most directly support the claim that improvisation relies on a large prepared repertoire rather than genuine spontaneous invention?",
    reasoning: "The passage's argument implies that experienced improvisers, having built a larger repertoire through practice, should be able to construct convincing 'spontaneous' performances more reliably than novices; evidence of exactly this — that practice/rehearsal time predicts perceived improvisational skill — would support the repertoire-based account over a genuine-spontaneous-invention account.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Performers who have rehearsed a wider range of patterns and phrases are consistently rated as more skilled improvisers", correct: true },
      { text: "Audiences cannot distinguish between improvised and scripted performances at all", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "This tests whether improvisation is perceptible as different from scripting, not specifically whether skill in it comes from a rehearsed repertoire." },
      { text: "Improvised performances are generally shorter than scripted ones", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Performance length doesn't test the passage's specific claim about a rehearsed repertoire underlying apparent spontaneity." },
      { text: "Improvisational theater has grown more popular in recent decades", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Popularity trends don't test the mechanism (rehearsed repertoire vs. genuine spontaneity) the passage's argument is about." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_improvisation_illusion",
    stem: "According to the passage, genuine spontaneity may be:",
    reasoning: "The passage's closing claim states genuine spontaneity 'may be less valuable to good improvisation than a large enough stock of prepared material to make planning invisible.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Less valuable to good improvisation than a large stock of prepared material", correct: true },
      { text: "The single most essential ingredient of good improvisation", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly ranks a prepared repertoire as potentially more valuable than genuine spontaneity itself." },
      { text: "Something entirely absent from all forms of live performance", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't claim spontaneity is entirely absent from performance generally, only that it may be less valuable than preparation to good improvisation specifically." },
      { text: "Impossible to define in any meaningful way", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage treats spontaneity as a definable concept it is actively comparing to prepared repertoire, not as undefinable." },
    ],
  },

  // --- cars_recipe_copyright (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_recipe_copyright",
    stem: "According to the passage, a chef generally cannot copyright a recipe itself because copyright law treats it as:",
    reasoning: "The passage states copyright law's explanation is that a recipe is 'a functional process, akin to an instruction manual, rather than an expressive work.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "A functional process, akin to an instruction manual, not an expressive work", correct: true },
      { text: "A trade secret automatically protected without registration", errorType: "outside_knowledge_not_supported_by_passage", why: "Trade secret law is a separate legal framework from copyright, and the passage discusses copyright's specific exclusion of functional processes, not trade secret protection." },
      { text: "A form of expression too short to qualify for any legal protection", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage attributes the exclusion to the functional/process nature of a recipe, not to its length." },
      { text: "Something that automatically belongs to the restaurant where it was created", errorType: "outside_knowledge_not_supported_by_passage", why: "Ownership by an employer is a separate legal issue from the functional-process reasoning the passage actually discusses." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_recipe_copyright",
    stem: "According to the passage, the theory behind excluding functional processes from copyright is that granting exclusive rights over a method would:",
    reasoning: "The passage states this would 'improperly restrict others from independently discovering and using the same functional solution.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Improperly restrict others from independently discovering and using the same functional solution", correct: true },
      { text: "Make it too easy for other chefs to freely use any recipe they want", errorType: "sign_or_direction_reversal", why: "The passage's theory is about preventing improper restriction, meaning the concern is over-restriction, not making copying too easy." },
      { text: "Immediately bankrupt the restaurant that created the recipe", errorType: "outside_knowledge_not_supported_by_passage", why: "Financial harm to the restaurant is not the theoretical justification the passage attributes to this copyright exclusion." },
      { text: "Violate international trade agreements", errorType: "outside_knowledge_not_supported_by_passage", why: "International trade law is not discussed in the passage's explanation for excluding functional processes from copyright." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_recipe_copyright",
    stem: "According to the passage, what aspect of a recipe's presentation actually can be copyrighted?",
    reasoning: "The passage states 'what can be protected is the specific expressive language used to describe the recipe, such as an accompanying essay or distinctive photography.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "The specific expressive language, such as an accompanying essay or photography", correct: true },
      { text: "The exact sequence of cooking steps themselves", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states 'never the underlying sequence of actions the recipe instructs a cook to perform' can be protected." },
      { text: "The specific quantities of each ingredient listed", errorType: "passage_detail_misread_or_over_extrapolated", why: "Ingredient quantities are part of the functional process the passage says is excluded from copyright protection." },
      { text: "The name of the dish alone", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses expressive language like essays or photography as protectable, not simply the dish's name." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_recipe_copyright",
    stem: "Based on the passage's reasoning, which of the following would be most analogous to a recipe's copyright status?",
    reasoning: "The passage's reasoning excludes functional processes (like the sequence of steps in a recipe) from copyright while protecting expressive presentation; a similar functional set of instructions — like an assembly manual's step sequence — would be analogously excluded from copyright as a functional process, even though accompanying illustrations or descriptive text could still be protected.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "The step-by-step sequence in a furniture assembly manual, as opposed to its accompanying illustrations", correct: true },
      { text: "A novel's unique plot and characters, fully protected by copyright", errorType: "outside_knowledge_not_supported_by_passage", why: "A novel's plot and characters are protected as expressive creative content, unlike a recipe's excluded functional process — this isn't analogous to the recipe situation." },
      { text: "A songwriter's original melody, fully protected by copyright", errorType: "outside_knowledge_not_supported_by_passage", why: "A melody is an expressive creative work under copyright, not a functional process like a recipe's steps, making this a poor analogy." },
      { text: "A patented mechanical invention, protected by patent law instead of copyright", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's reasoning is specifically about copyright's functional-process exclusion, not about how patent law separately protects inventions." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_recipe_copyright",
    stem: "According to the passage, many people find the recipe-copyright gap to be:",
    reasoning: "The passage states this 'strikes many people as an odd gap in intellectual property protection given how much creative work can go into a dish.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "An odd gap in intellectual property protection", correct: true },
      { text: "Completely unsurprising and obviously correct", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly describes this as striking people as 'odd,' not as obviously correct or unsurprising." },
      { text: "A recent legal change that overturned centuries of precedent", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't frame this as a recent legal change; it discusses the standing rule and its rationale." },
      { text: "A rule that applies only to desserts, not other dishes", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't restrict this rule to any specific category of dish like desserts." },
    ],
  },

  // --- cars_small_talk_function (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_small_talk_function",
    stem: "According to the passage, small talk is frequently dismissed as empty because:",
    reasoning: "The passage states small talk is dismissed 'precisely because so little substantive information is exchanged.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "So little substantive information is exchanged", correct: true },
      { text: "It is always conducted between close friends only", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage describes small talk as occurring between near-strangers, not exclusively close friends, and this isn't the reason given for its dismissal." },
      { text: "It takes an unusually long time to complete", errorType: "outside_knowledge_not_supported_by_passage", why: "Duration is not the reason the passage gives for small talk being dismissed as empty." },
      { text: "It is technically illegal in professional settings", errorType: "outside_knowledge_not_supported_by_passage", why: "Legality is not discussed anywhere in the passage." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_small_talk_function",
    stem: "According to the passage, sociolinguists challenge the dismissal of small talk by arguing its real function is:",
    reasoning: "The passage states 'small talk's real function is not informational but relational: it signals...that both parties are willing to engage cooperatively.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "Relational — signaling willingness to engage cooperatively", correct: true },
      { text: "Purely informational, just as critics assume", errorType: "sign_or_direction_reversal", why: "The passage explicitly states the real function is 'not informational,' contradicting this option." },
      { text: "Legal — establishing a formal verbal contract between parties", errorType: "outside_knowledge_not_supported_by_passage", why: "No legal function is attributed to small talk in the passage." },
      { text: "Purely aesthetic, valued for its pleasant sound", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage attributes small talk's function to establishing social trust, not to aesthetic sound qualities." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_small_talk_function",
    stem: "The passage's handshake analogy is used to argue that judging small talk by its informational content is:",
    reasoning: "The passage states this is 'analogous to judging a handshake by how much it tells you about someone's grip strength — measuring the wrong thing.'",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Measuring the wrong thing, since the real content lies in the willingness to perform the exchange at all", correct: true },
      { text: "A perfectly appropriate and accurate way to evaluate its true value", errorType: "sign_or_direction_reversal", why: "The passage explicitly uses this analogy to argue the informational-content standard is the wrong measure, not an appropriate one." },
      { text: "Evidence that handshakes and small talk serve identical physical functions", errorType: "outside_knowledge_not_supported_by_passage", why: "The analogy illustrates a shared logical error in evaluation standards, not a claim that the two behaviors serve identical physical functions." },
      { text: "Proof that small talk should be replaced with handshakes entirely", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage uses the handshake as an illustrative analogy, not as a proposal to replace one behavior with the other." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_small_talk_function",
    stem: "Which finding would most directly support the passage's relational account of small talk?",
    reasoning: "The relational account predicts small talk's value lies in signaling cooperative willingness rather than conveying information; a finding that people who decline to engage in small talk before a business meeting are perceived as less trustworthy or cooperative, regardless of what is actually said, would directly support this relational function.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "People who skip small talk before a business meeting are rated as less trustworthy, even though no substantive information was exchanged either way", correct: true },
      { text: "People remember the specific content of small talk exchanges very accurately", correct: false, errorType: "true_statement_that_does_not_answer_the_question", why: "Accurate content recall would actually suggest an informational function, working against, not supporting, the passage's relational account." },
      { text: "Small talk is more common in some languages than others", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Cross-linguistic prevalence doesn't specifically test whether small talk's function is relational versus informational." },
      { text: "People engage in small talk more often in the morning than in the evening", correct: false, errorType: "outside_knowledge_not_supported_by_passage", why: "Time-of-day patterns don't bear on whether small talk's core function is relational rather than informational." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_small_talk_function",
    stem: "According to the passage, small talk establishes what the passage calls a 'minimal baseline of social trust' before:",
    reasoning: "The passage states this trust is established 'before (or instead of) any substantive exchange occurs.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Any substantive exchange occurs, or in place of one entirely", correct: true },
      { text: "The two parties have ever met in person", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses small talk occurring during an in-person or ongoing interaction between near-strangers, not as something preceding any meeting at all." },
      { text: "A formal legal contract is signed between the parties", errorType: "outside_knowledge_not_supported_by_passage", why: "Legal contracts are not part of the passage's discussion of small talk's relational function." },
      { text: "One party has fully verified the other's identity", errorType: "outside_knowledge_not_supported_by_passage", why: "Identity verification is not the process the passage describes small talk as preceding; it describes it as preceding substantive conversational exchange." },
    ],
  },
];
