import type { ItemDef } from "./types";

export const itemsCars: ItemDef[] = [
  // --- cars_revision (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_revision",
    stem: "The passage suggests that writers who are uncomfortable with their own early drafts may be making which error?",
    reasoning: "The passage's final sentence states this discomfort 'may be a category error: they are judging a tool by the standards of a finished product' — directly answerable only from the passage.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Judging an instrument of discovery by the standards of a finished product", correct: true },
      { text: "Underestimating how much time revision actually takes", errorType: "passage_detail_misread_or_over_extrapolated", why: "Introduces a time-management claim the passage never makes." },
      { text: "Failing to outline before writing a first draft", errorType: "outside_knowledge_not_supported_by_passage", why: "Imports generic writing-advice knowledge not present in the passage." },
      { text: "Revising too early in the writing process", errorType: "true_statement_that_does_not_answer_the_question", why: "Plausible-sounding writing advice, but not the error the passage names." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_revision",
    stem: "Which of the following, if true, would most directly challenge the passage's central claim?",
    reasoning: "The passage argues first drafts serve discovery, not final-product quality. A finding that skipping drafting entirely (going straight to a polished version) produces equally strong discovery of ideas would undercut the claim that drafts are a distinct, necessary kind of instrument.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Writers who skip drafting and write final versions directly report discovering just as many new ideas about their subject", correct: true },
      { text: "Most professional writers produce more than one draft before publication", errorType: "true_statement_that_does_not_answer_the_question", why: "Consistent with, not a challenge to, the passage's claim." },
      { text: "Editing software has made revision faster than in previous decades", errorType: "passage_detail_misread_or_over_extrapolated", why: "Irrelevant to whether drafts serve a discovery function." },
      { text: "Some writers feel anxious when rereading their own first drafts", errorType: "true_statement_that_does_not_answer_the_question", why: "Restates a premise from the passage rather than challenging the conclusion." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_revision",
    stem: "The passage's claim that a first draft is 'a different kind of object entirely' from the finished piece is best understood as:",
    reasoning: "The passage sets up and then argues against the common view that a draft is merely a weak version of the final text, replacing it with the claim that a draft serves a distinct discovery function — a rhetorical move within the passage's own argument.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "A rejection of the common view that a draft is simply a lesser version of the final text", correct: true },
      { text: "An empirical claim requiring outside statistical evidence to evaluate", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage presents this as an interpretive argument, not a statistical claim needing external data." },
      { text: "A minor aside unrelated to the passage's main argument", errorType: "true_statement_that_does_not_answer_the_question", why: "This claim is actually central to, not tangential to, the passage's overall argument." },
      { text: "A direct quotation from a professional writer", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage presents this as the author's own claim, not an attributed quotation." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_revision",
    stem: "Within the passage's argument, the phrase 'artifacts whose main value was used up in the writing of them' functions primarily to:",
    reasoning: "This phrase elaborates the passage's central distinction: a draft's value lies in the process of writing it (discovery), not in the artifact persisting as a finished product — reinforcing the discovery-versus-statement framing established earlier.",
    difficulty: 0.5,
    sirs: 2,
    options: [
      { text: "Reinforce the idea that a draft's value comes from the process of writing it, not from the resulting text itself", correct: true },
      { text: "Introduce a new, unrelated argument about writers' compensation", errorType: "passage_detail_misread_or_over_extrapolated", why: "'Value' here refers to the draft's function in the writing process, not financial compensation." },
      { text: "Suggest that drafts should be discarded immediately after writing", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage doesn't recommend discarding drafts; it reframes their purpose, not their disposal." },
      { text: "Contradict the passage's earlier claim about discovery", errorType: "passage_detail_misread_or_over_extrapolated", why: "The phrase supports and extends the discovery claim rather than contradicting it." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_revision",
    stem: "According to the passage, what is the primary 'job' of a first draft?",
    reasoning: "The passage states directly that a first draft's job 'is to discover what the piece is about rather than to state it.'",
    difficulty: 0.1,
    sirs: 1,
    options: [
      { text: "To discover what the piece is about", correct: true },
      { text: "To state the piece's argument as clearly as possible", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly assigns this 'stating' function to the finished piece, not the first draft." },
      { text: "To impress an eventual editor", errorType: "outside_knowledge_not_supported_by_passage", why: "Not a function the passage attributes to a first draft." },
      { text: "To be published with minimal further changes", errorType: "outside_knowledge_not_supported_by_passage", why: "Contradicts the passage's framing of a draft as a discovery tool, not a near-final product." },
    ],
  },

  // --- cars_walkability (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_walkability",
    stem: "According to the passage, cities celebrated for walkability today typically achieved it:",
    reasoning: "The passage states walkability 'survived as an accident of age,' having been laid out before cars existed to demand different infrastructure, not through deliberate pedestrian-first design.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "By accident, through having been built before the automobile existed", correct: true },
      { text: "Through deliberate pedestrian-first design from the start", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states walkability was rarely designed with pedestrians foremost in mind." },
      { text: "By banning automobiles from their downtown areas", errorType: "outside_knowledge_not_supported_by_passage", why: "Not a mechanism the passage describes at all." },
      { text: "Through recent large public investment in pedestrian infrastructure", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage attributes walkability to historical age and pre-automobile layout, not recent investment." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_walkability",
    stem: "The passage argues that walkability is 'not a style that can simply be applied to a newer district.' This claim is best supported, within the passage, by the point that walkability:",
    reasoning: "The passage's supporting reasoning is that walkability results from constraints (narrow lots, mixed uses, an unwidened grid) that a modern car-oriented development process would ordinarily discard — meaning it can't just be added stylistically.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Depends on constraints a car-oriented development process would typically discard", correct: true },
      { text: "Requires a much larger population than most newer districts have", errorType: "outside_knowledge_not_supported_by_passage", why: "Population size is never mentioned as a factor in the passage." },
      { text: "Is primarily a matter of building attractive facades", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage locates walkability in structural/planning constraints, not aesthetic style like facades." },
      { text: "Only works in coastal cities", errorType: "outside_knowledge_not_supported_by_passage", why: "Geography is never discussed in the passage as a relevant factor." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_walkability",
    stem: "Which finding would most strongly support the passage's argument about the origins of walkability?",
    reasoning: "The passage's argument is that walkability results from pre-automobile constraints, not deliberate design; a finding that new developments actively imposing those same constraints (narrow streets, mixed use) also become walkable would support the claim that the constraints — not intentional design philosophy — are what matters.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "New developments that impose narrow streets and mixed uses become walkable regardless of the developers' stated design philosophy", correct: true },
      { text: "Newer developments explicitly marketed as 'walkable' sell for higher prices", errorType: "true_statement_that_does_not_answer_the_question", why: "Says something about market demand for walkability, not about what actually produces it." },
      { text: "Older cities have more historical monuments than newer ones", errorType: "outside_knowledge_not_supported_by_passage", why: "Irrelevant to the mechanism of walkability the passage discusses." },
      { text: "Pedestrians report enjoying walkable neighborhoods more than car-dependent ones", errorType: "true_statement_that_does_not_answer_the_question", why: "Speaks to the value of walkability, not to the passage's specific claim about its historical origin." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_walkability",
    stem: "According to the passage, a planner seeking to create a walkable neighborhood is, in effect:",
    reasoning: "The passage states such a planner 'is not selecting an aesthetic but reintroducing a set of restrictions that a car-oriented planning process would ordinarily discard' — reframing the planner's task as restoring constraints, not choosing a style.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Reintroducing restrictions a car-oriented process would normally discard", correct: true },
      { text: "Selecting a decorative style independent of any functional constraints", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly denies this framing, stating the planner is 'not selecting an aesthetic.'" },
      { text: "Petitioning to widen streets to accommodate more foot traffic", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage associates wider streets with car-oriented, not walkable, design." },
      { text: "Waiting for automobile use to decline naturally over time", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage describes active reintroduction of constraints, not passive waiting." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_walkability",
    stem: "The passage identifies which of the following as a constraint contributing to older cities' walkability?",
    reasoning: "The passage lists 'narrow lots, mixed uses packed close together, a street grid never widened to accommodate car speeds' as the relevant constraints.",
    difficulty: 0.1,
    sirs: 1,
    options: [
      { text: "A street grid never widened for car speeds", correct: true },
      { text: "Zoning laws mandating single-family housing only", errorType: "outside_knowledge_not_supported_by_passage", why: "Not a constraint mentioned anywhere in the passage." },
      { text: "Government subsidies for public transit", errorType: "outside_knowledge_not_supported_by_passage", why: "Subsidies are never discussed in the passage." },
      { text: "Strict height limits on all new buildings", errorType: "outside_knowledge_not_supported_by_passage", why: "Height limits are not among the constraints the passage identifies." },
    ],
  },

  // --- cars_monuments (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_monuments",
    stem: "According to the passage, a monument is better understood as:",
    reasoning: "The passage directly states monuments are 'better understood as arguments frozen at the moment they were persuasive,' contrasted with the common view of a monument as a 'settled verdict' or neutral record.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "An argument frozen at the moment it was persuasive", correct: true },
      { text: "A neutral, objective record of historical events", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly argues against treating a monument as a neutral record." },
      { text: "A universally agreed-upon symbol with no historical context", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage emphasizes that monuments reflect the specific era that built them, not universal agreement." },
      { text: "A purely aesthetic object with no persuasive function", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames monuments as fundamentally persuasive/argumentative, not merely decorative." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_monuments",
    stem: "The passage's claim that removing a monument is 'not an act of erasing history' depends most directly on its earlier claim that:",
    reasoning: "The passage's logic is that since a monument was never history itself but only one era's argument about how to remember the past, removing or recontextualizing it updates an argument rather than erasing a historical record.",
    difficulty: 0.5,
    sirs: 2,
    options: [
      { text: "A monument was never a neutral record of history, only an argument built by a particular era", correct: true },
      { text: "Most monuments are physically difficult and expensive to remove", errorType: "outside_knowledge_not_supported_by_passage", why: "Cost or difficulty of removal is never mentioned in the passage and is irrelevant to this specific claim's logic." },
      { text: "Historians rarely agree on how to interpret any given monument", errorType: "outside_knowledge_not_supported_by_passage", why: "Historian disagreement is not the basis the passage gives for this claim." },
      { text: "Most monuments depict military rather than political figures", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage never restricts its claim to a specific category of monument subject." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_monuments",
    stem: "A defender of keeping a controversial monument unchanged argues that doing so 'preserves history as it actually happened.' Based on the passage's argument, this defense would most likely be countered by pointing out that:",
    reasoning: "The passage's argument is that a monument was never a neutral historical record to begin with — it was always an argument reflecting the priorities of the era that built it — so 'preserving it as history' misunderstands what a monument actually is or was.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "The monument itself was never a neutral historical record, only one era's argument about the past", correct: true },
      { text: "Removing monuments is illegal in most jurisdictions", errorType: "outside_knowledge_not_supported_by_passage", why: "Legality is a separate practical question the passage never raises." },
      { text: "Most controversial monuments are not historically accurate in their factual details", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's objection is conceptual (what a monument is), not about factual accuracy of depicted details." },
      { text: "The original builders of the monument are no longer alive to defend it", errorType: "outside_knowledge_not_supported_by_passage", why: "Not a point the passage makes or relies on in its argument." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_monuments",
    stem: "The passage states that the choice of 'whom to commemorate, in what pose, and at what scale' reflects:",
    reasoning: "The passage attributes these choices to reflecting 'the priorities of the era that built the monument at least as much as the era it depicts' — a claim about whose values a monument actually encodes.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "The priorities of the era that built the monument, at least as much as the era it depicts", correct: true },
      { text: "Only the objective historical importance of the person depicted", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly attributes these choices to the builders' era's priorities, not to objective historical importance alone." },
      { text: "Random artistic preference with no connection to any era's values", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames these choices as meaningfully reflecting priorities, not as arbitrary." },
      { text: "The preferences of the depicted historical figure themselves", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage attributes the choices to the builders' era, not to the depicted figure's own preferences." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_monuments",
    stem: "According to the passage, recontextualizing a monument represents:",
    reasoning: "The passage frames recontextualization as 'an act of updating an argument,' consistent with treating a monument as an argument rather than a settled historical fact.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "An act of updating an argument, not erasing history", correct: true },
      { text: "A form of historical censorship that destroys evidence", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly frames this as updating an argument, the opposite of erasing evidence." },
      { text: "A purely legal process with no interpretive content", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage frames this as an interpretive, argumentative act, not a narrowly legal one." },
      { text: "An act only appropriate for monuments over a century old", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage places no age restriction on which monuments this reasoning applies to." },
    ],
  },

  // --- cars_nostalgia (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_nostalgia",
    stem: "According to the passage, the common dismissal of nostalgia assumes that nostalgia's function is:",
    reasoning: "The passage states the common dismissal 'assumes nostalgia's function is descriptive — that it purports to be an accurate report on how things were.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Descriptive, an accurate report of how things were", correct: true },
      { text: "Evaluative, a claim about what mattered", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage assigns the evaluative reading to the more charitable alternative view, not the common dismissal." },
      { text: "Purely biological, an automatic brain response", errorType: "outside_knowledge_not_supported_by_passage", why: "Not a function the passage attributes to either the common view or the alternative." },
      { text: "Predictive, a forecast of future events", errorType: "outside_knowledge_not_supported_by_passage", why: "Prediction is never discussed as a function of nostalgia in the passage." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_nostalgia",
    stem: "The passage's 'more charitable reading' of nostalgia reframes it as making a claim about:",
    reasoning: "The passage states the charitable reading treats nostalgia as 'a way of marking which relationships, places, or practices a person judges to have been worth having' — an evaluative claim about worth, not a factual claim about accuracy.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "What was worth having, rather than what literally happened", correct: true },
      { text: "The literal, factual accuracy of remembered events", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly moves away from treating nostalgia as a claim about factual accuracy." },
      { text: "Which specific year a memory occurred in", errorType: "outside_knowledge_not_supported_by_passage", why: "Chronological precision is not the concern the passage raises." },
      { text: "Whether other people share the same memory", errorType: "outside_knowledge_not_supported_by_passage", why: "Interpersonal agreement about memories is not addressed in the passage." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_nostalgia",
    stem: "The passage states that nostalgia 'can misfire.' Under the passage's own framework, what kind of failure does this represent?",
    reasoning: "The passage explicitly states this failure is 'a failure of judgment, not a categorical failure of honesty' — meaning nostalgia can wrongly evaluate what was worth valuing, without being inherently dishonest about facts.",
    difficulty: 0.5,
    sirs: 2,
    options: [
      { text: "A failure of judgment about what was worth valuing, not a failure of honesty", correct: true },
      { text: "A failure of honesty, since misfired nostalgia is a form of lying", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly distinguishes this from a failure of honesty." },
      { text: "A memory disorder requiring clinical treatment", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage frames this in terms of evaluative judgment, not clinical memory pathology." },
      { text: "Proof that nostalgia is always a distortion of the past", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly denies that this failure implies nostalgia is inherently a distortion." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_nostalgia",
    stem: "Which scenario would the passage's 'more charitable reading' of nostalgia most easily accommodate as a legitimate (non-misfiring) case?",
    reasoning: "Under the evaluative reading, legitimate nostalgia marks something genuinely worth having that is now gone — e.g., valuing a close friendship that has ended — rather than making a false factual claim, so this scenario fits without needing to defend factual accuracy.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "A person feeling nostalgic for a close friendship that genuinely mattered to them, now that it has ended", correct: true },
      { text: "A person insisting a past event happened exactly as they remember it, contradicted by video evidence", errorType: "outside_knowledge_not_supported_by_passage", why: "This is precisely the descriptive/factual-accuracy framing the passage's charitable reading moves away from, so it fits poorly." },
      { text: "A person using nostalgia as an excuse to avoid making any decisions in the present", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes this kind of excuse-making as an example of nostalgia misfiring, not a legitimate case." },
      { text: "A person nostalgic for an event that never actually occurred", errorType: "outside_knowledge_not_supported_by_passage", why: "This directly raises a factual-accuracy problem the evaluative reading is meant to sidestep, making it a poor fit for a 'legitimate' case." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_nostalgia",
    stem: "According to the passage, nostalgia is often dismissed as:",
    reasoning: "The passage's opening sentence states nostalgia 'is often dismissed as sentimental self-indulgence, a refusal to see the past clearly.'",
    difficulty: 0.1,
    sirs: 1,
    options: [
      { text: "Sentimental self-indulgence and a refusal to see the past clearly", correct: true },
      { text: "A rare and clinically significant psychological disorder", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage never frames nostalgia as a clinical disorder." },
      { text: "A recently discovered phenomenon with no history of philosophical discussion", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't comment on how recently or long nostalgia has been discussed." },
      { text: "A uniquely modern problem caused by social media", errorType: "outside_knowledge_not_supported_by_passage", why: "Social media and modernity are never mentioned in the passage." },
    ],
  },

  // --- cars_translation (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_translation",
    stem: "According to the passage, the common complaint about translation treats it as:",
    reasoning: "The passage states the common complaint 'treats translation as a lossy copy of an original, judged by how much of the source it fails to preserve.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "A lossy copy judged by how much of the original it fails to preserve", correct: true },
      { text: "An entirely new, unrelated work of literature", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames the common complaint as treating translation in relation to a source it's compared against, not as an unrelated work." },
      { text: "A process that always improves on the original", errorType: "passage_detail_misread_or_over_extrapolated", why: "The common complaint the passage describes centers on loss, not improvement." },
      { text: "A purely mechanical, word-for-word substitution", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't characterize the common complaint in these mechanical terms." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_translation",
    stem: "The passage argues that describing translation only as loss is incomplete because it ignores:",
    reasoning: "The passage states translation 'does not only subtract, it also introduces' new texture for readers who never had access to the source — the addition process the loss-only framing ignores.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "The way translation also adds new texture not present in the original", correct: true },
      { text: "The financial cost of hiring professional translators", errorType: "outside_knowledge_not_supported_by_passage", why: "Cost is never discussed in the passage." },
      { text: "The fact that most translations are eventually revised multiple times", errorType: "outside_knowledge_not_supported_by_passage", why: "Revision history of translations is not a topic the passage raises." },
      { text: "The possibility that a translation might be more popular than the original", errorType: "outside_knowledge_not_supported_by_passage", why: "Relative popularity is not the missing half of the picture the passage identifies." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_translation",
    stem: "The passage's example of a translator working between languages with 'different grammatical genders, different densities of formal address, or different poetic traditions' is used primarily to illustrate:",
    reasoning: "This example supports the passage's central claim that a translator actively makes choices that add texture the original never had, showing concretely how structural differences between languages create opportunities for addition, not just loss.",
    difficulty: 0.5,
    sirs: 2,
    options: [
      { text: "How structural differences between languages create opportunities for a translator to add new texture", correct: true },
      { text: "Why some languages are objectively superior to others for literary work", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage makes no claim about languages being superior or inferior to one another." },
      { text: "Why literary translation should be avoided between very different languages", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage uses this example to support translation's added value, not to argue against attempting it." },
      { text: "That translators frequently mistranslate due to these differences", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage frames these differences as a source of added texture, not as a source of mistakes." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_translation",
    stem: "Which finding would most directly support the passage's claim that translation 'introduces' rather than only subtracts?",
    reasoning: "The passage's claim is specifically about translation adding something new for readers; evidence that readers of a translation notice and value stylistic effects entirely absent from the original would directly support this 'introduces' claim.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Readers of a translated poem report noticing rhythmic or tonal effects entirely absent from the original text", correct: true },
      { text: "Readers of the original and the translation report identical emotional reactions", errorType: "outside_knowledge_not_supported_by_passage", why: "Identical reactions would suggest no meaningful addition or loss occurred, rather than supporting the 'introduces' claim." },
      { text: "Translators are paid less than original authors on average", errorType: "outside_knowledge_not_supported_by_passage", why: "Compensation has no bearing on whether translation adds new textual qualities." },
      { text: "Most readers prefer to read literature in the original language when possible", errorType: "outside_knowledge_not_supported_by_passage", why: "A stated preference for originals doesn't bear on whether translations add something new." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_translation",
    stem: "According to the passage, who specifically benefits from the 'texture' a translation adds?",
    reasoning: "The passage specifies this added texture is for 'readers who never had access to the source in the first place' — that is, readers of the translation rather than the original.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Readers who never had access to the original source text", correct: true },
      { text: "The original author of the source text", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage identifies readers of the translation, not the original author, as the beneficiaries." },
      { text: "Professional literary critics exclusively", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage does not restrict this benefit to critics specifically." },
      { text: "Bilingual readers who can compare both versions", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage specifically highlights readers without access to the source, the opposite of bilingual comparison readers." },
    ],
  },

  // --- cars_attention_economy (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_attention_economy",
    stem: "According to the passage, what is the actual scarce resource being allocated in the digital media economy, per the economists described?",
    reasoning: "The passage states economists increasingly describe 'attention itself as the scarce resource being allocated, with content serving as the mechanism of allocation.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Attention", correct: true },
      { text: "Content", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage identifies content as the mechanism of allocation, not the scarce resource itself." },
      { text: "Advertising revenue", errorType: "passage_detail_misread_or_over_extrapolated", why: "Advertising revenue is described as what attention is resold for, not the scarce resource itself." },
      { text: "Internet bandwidth", errorType: "outside_knowledge_not_supported_by_passage", why: "Bandwidth is never mentioned in the passage as the resource in question." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_attention_economy",
    stem: "The passage's claim that 'a free article or video is not really free' is best explained by which subsequent point in the passage?",
    reasoning: "The passage immediately explains this claim: 'the reader or viewer pays in the currency of attention, which is then resold to advertisers' — attention is the actual payment, even though no money changes hands.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "The reader pays in attention, which is then resold to advertisers", correct: true },
      { text: "Most free content is actually funded by government subsidies", errorType: "outside_knowledge_not_supported_by_passage", why: "Government subsidies are never mentioned in the passage." },
      { text: "Free content is typically of much lower quality than paid content", errorType: "outside_knowledge_not_supported_by_passage", why: "Content quality comparisons are not part of the passage's argument here." },
      { text: "Readers eventually have to pay a subscription fee", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's point is about attention as payment, not about an eventual monetary fee." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_attention_economy",
    stem: "The passage argues that because attention 'cannot be saved for later or borrowed against future income,' competition for it tends toward:",
    reasoning: "The passage directly connects this property of attention to competition favoring 'novelty, outrage, and interruption' — qualities that reliably capture attention in the moment, since future attention can't be secured in advance.",
    difficulty: 0.5,
    sirs: 2,
    options: [
      { text: "Novelty, outrage, and interruption, which reliably capture attention immediately", correct: true },
      { text: "Long-form, carefully researched journalism", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage argues the opposite — that this market structure disadvantages content requiring sustained attention." },
      { text: "Slow, deliberate storytelling that rewards patience", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's argument is that competition favors the opposite qualities, given attention's non-storable nature." },
      { text: "Subscription-based business models exclusively", errorType: "outside_knowledge_not_supported_by_passage", why: "Business model type is not the outcome the passage links to attention's non-storable nature." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_attention_economy",
    stem: "The passage's argument implies that a media company designed to reward long-term reader retention over immediate engagement would likely face which challenge?",
    reasoning: "If markets structured around unstorable attention systematically favor immediate-capture content, a company optimizing for long-term retention over instant engagement would be competing against this same market pressure toward novelty/outrage, putting it at a competitive disadvantage under the passage's own logic.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Competitive disadvantage against content optimized to capture immediate attention", correct: true },
      { text: "No particular challenge, since attention markets favor patient, sustained content", errorType: "outside_knowledge_not_supported_by_passage", why: "This contradicts the passage's explicit argument that the market favors immediate-capture qualities instead." },
      { text: "Difficulty finding advertisers willing to pay for any attention at all", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's argument concerns what kind of content wins attention, not whether advertisers pay for attention in general." },
      { text: "Legal restrictions on subscription-based revenue models", errorType: "outside_knowledge_not_supported_by_passage", why: "Legal issues around subscriptions are not discussed anywhere in the passage." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_attention_economy",
    stem: "According to the passage, critics argue that a market structured around capturing attention will:",
    reasoning: "The passage states critics argue such a market 'will systematically underproduce content that rewards sustained attention, however much any individual buyer might prefer it.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Systematically underproduce content that rewards sustained attention", correct: true },
      { text: "Produce an ideal balance of both immediate and sustained-attention content", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's critics argue the opposite — a systematic shortfall of sustained-attention content." },
      { text: "Eventually collapse entirely due to advertiser withdrawal", errorType: "outside_knowledge_not_supported_by_passage", why: "Market collapse is not a claim the passage makes." },
      { text: "Have no measurable effect on what content gets produced", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's entire argument is about a specific, predictable effect on content production." },
    ],
  },

  // --- cars_ritual (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_ritual",
    stem: "According to the passage, the puzzle sociologists have noted is that many people who no longer hold certain religious beliefs still:",
    reasoning: "The passage states the puzzle is that people 'who no longer hold the doctrinal beliefs associated with a tradition continue to observe its rituals.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "Continue to observe the tradition's rituals", correct: true },
      { text: "Actively campaign against all religious institutions", errorType: "outside_knowledge_not_supported_by_passage", why: "Activism against religious institutions is not the puzzle the passage describes." },
      { text: "Adopt an entirely new set of unrelated rituals", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes continuing the same original rituals, not adopting new unrelated ones." },
      { text: "Report feeling no emotional connection to their cultural background", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage's puzzle concerns continued ritual practice, not lack of emotional connection." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_ritual",
    stem: "The 'habit' explanation of persistent ritual, as described in the passage, predicts that ritual observance should:",
    reasoning: "The passage describes the habit explanation as treating ritual as 'a vestige that will fade once the beliefs that originally motivated it are gone' — implying it predicts eventual decline as belief fades further.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Eventually fade once the motivating beliefs are entirely gone", correct: true },
      { text: "Persist indefinitely regardless of belief", errorType: "passage_detail_misread_or_over_extrapolated", why: "This is actually closer to the competing explanation's prediction, not the habit explanation's." },
      { text: "Intensify as beliefs fade further", errorType: "passage_detail_misread_or_over_extrapolated", why: "The habit explanation predicts fading, not intensifying, as the passage describes it." },
      { text: "Transform into an entirely new belief system", errorType: "outside_knowledge_not_supported_by_passage", why: "Not a prediction the passage attributes to the habit explanation." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_ritual",
    stem: "The passage's competing explanation holds that ritual and belief were 'never as tightly coupled' as the habit account assumes, because ritual:",
    reasoning: "The passage states this competing view holds that ritual 'performs social work — marking transitions, binding a group together at a shared moment — that does not depend on the participants sharing a metaphysical commitment.'",
    difficulty: 0.5,
    sirs: 2,
    options: [
      { text: "Performs social work that doesn't depend on shared metaphysical belief", correct: true },
      { text: "Was invented independently of any religious tradition", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage discusses rituals tied to religious traditions, not rituals invented independently of them." },
      { text: "Requires stronger belief than doctrine does to be effective", errorType: "passage_detail_misread_or_over_extrapolated", why: "The competing explanation argues ritual's social function doesn't depend on belief at all, not that it requires more belief." },
      { text: "Is entirely a modern invention with no historical basis", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't make any claim about ritual being a recent invention." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_ritual",
    stem: "If researchers found that secular communal ceremonies (with no religious content at all) reliably produce the same group-bonding effects as traditional religious rituals, this finding would most directly support:",
    reasoning: "This finding would show ritual's bonding function can operate entirely independent of religious belief or content, directly supporting the passage's competing explanation that ritual's social work doesn't depend on a shared metaphysical commitment.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "The passage's competing explanation, that ritual's social function doesn't depend on shared belief", correct: true },
      { text: "The habit explanation, that ritual is a fading vestige of past belief", errorType: "outside_knowledge_not_supported_by_passage", why: "A secular ceremony producing the same effects has no prior religious belief to be a 'vestige' of, undermining rather than supporting the habit account." },
      { text: "Neither explanation, since the passage only discusses religious rituals", errorType: "true_statement_that_does_not_answer_the_question", why: "While the passage's examples are religious, its competing explanation's underlying logic — social function independent of belief — directly extends to and is supported by this secular finding." },
      { text: "The claim that all rituals require formal religious institutions to be effective", errorType: "outside_knowledge_not_supported_by_passage", why: "The hypothetical finding is specifically about rituals without religious content, contradicting this claim." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_ritual",
    stem: "According to the passage, if the competing (non-habit) explanation of ritual is correct, the persistence of ritual after belief fades should be understood as:",
    reasoning: "The passage states that under the competing account, this persistence 'is not a contradiction to be explained away but evidence that ritual was doing its own work all along.'",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "Evidence that ritual was doing its own social work all along, not a contradiction", correct: true },
      { text: "A contradiction that sociologists have yet to resolve", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly states this is not a contradiction under the competing account." },
      { text: "Proof that the original religious beliefs were never sincerely held", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage makes no claim about the sincerity of originally held beliefs." },
      { text: "A sign that the ritual will disappear within a generation", errorType: "outside_knowledge_not_supported_by_passage", why: "This prediction belongs to the habit explanation, not the competing account being described here." },
    ],
  },

  // --- cars_authorship (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_authorship",
    stem: "According to the passage, which groups are described as reshaping a text during its creation?",
    reasoning: "The passage explicitly lists 'editors reshape structure, workshop peers redirect arguments' as examples of collaborative reshaping during a text's creation.",
    difficulty: 0.1,
    sirs: 1,
    options: [
      { text: "Editors and workshop peers", correct: true },
      { text: "Only literary critics after publication", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage discusses reshaping during creation, not critical response after publication." },
      { text: "Government censors", errorType: "outside_knowledge_not_supported_by_passage", why: "Censorship is never mentioned in the passage." },
      { text: "Publishing-house marketing departments", errorType: "outside_knowledge_not_supported_by_passage", why: "Marketing departments are not mentioned as reshaping the text itself." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_authorship",
    stem: "The passage states that even solitary drafting 'depends on a body of prior work the author has absorbed.' This point is used to argue that:",
    reasoning: "This point extends the passage's argument beyond obvious collaborators (editors, peers) to show that even seemingly solitary writing is never fully independent, since it draws on and continues prior work — reinforcing the case against the 'solitary author' image.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "Even apparently solitary writing is not fully independent of outside influence", correct: true },
      { text: "Plagiarism is more common than most people believe", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage is making a point about influence and continuity, not about plagiarism specifically." },
      { text: "Solitary writers produce lower-quality work than collaborative ones", errorType: "outside_knowledge_not_supported_by_passage", why: "No quality comparison is made in the passage." },
      { text: "Prior works should always be cited explicitly in a text", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage makes no argument about citation practices." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_authorship",
    stem: "The passage describes two conclusions people draw from evidence against solitary authorship. The second view, that individual authorship isn't erased by collaboration, rests on the idea that:",
    reasoning: "The passage states this second view holds that 'collaboration at every stage does not erase the meaningful sense in which one person made the decisive choices that give a text its particular shape.'",
    difficulty: 0.5,
    sirs: 2,
    options: [
      { text: "One person still makes the decisive choices that give the text its particular shape", correct: true },
      { text: "Collaboration is actually rare in most creative fields", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage assumes collaboration is common and asks what follows from it, not that it's rare." },
      { text: "Legal credit should always go to the original editor, not the writer", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage does not make a claim about legal credit assignment favoring editors." },
      { text: "Workshop peers deserve equal authorship credit on every project", errorType: "outside_knowledge_not_supported_by_passage", why: "This is closer to the first view the passage describes (authorship as a fiction), not the second view being asked about." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_authorship",
    stem: "Which finding would most challenge the passage's second view (that meaningful individual authorship survives collaboration)?",
    reasoning: "The second view depends on there being an identifiable individual who makes the decisive shaping choices; evidence that final creative decisions are consistently made by group consensus rather than any one person would undercut the claim that one person's choices give a text its particular shape.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Studies showing final creative decisions are typically made by group consensus, with no single decisive voice", correct: true },
      { text: "Studies showing most editors have minimal influence on a text's content", errorType: "outside_knowledge_not_supported_by_passage", why: "This would actually support, not challenge, the idea that one person retains the decisive role." },
      { text: "Studies showing readers cannot identify a text's author from writing style alone", errorType: "outside_knowledge_not_supported_by_passage", why: "This concerns stylistic detectability, not who actually made the text's decisive creative choices." },
      { text: "Studies showing collaborative writing takes longer to complete than solitary writing", errorType: "outside_knowledge_not_supported_by_passage", why: "Timing has no direct bearing on whether one person's choices remain decisive." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_authorship",
    stem: "According to the passage, the first view concludes that individual authorship is:",
    reasoning: "The passage states some conclude 'individual authorship is therefore a legal fiction useful mainly for assigning credit and liability.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "A legal fiction useful mainly for assigning credit and liability", correct: true },
      { text: "A biologically hardwired human trait", errorType: "outside_knowledge_not_supported_by_passage", why: "Biology is never invoked in the passage's discussion of this view." },
      { text: "An outdated concept that no serious scholar still uses", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage presents this as one of two live, contested views, not a settled or abandoned concept." },
      { text: "A concept unique to modern digital publishing", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't tie this view to any particular era or publishing format." },
    ],
  },

  // --- cars_expertise (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_expertise",
    stem: "According to the passage, the common definition of expertise treats it as:",
    reasoning: "The passage opens by describing this common definition: 'expertise as accumulated correct answers: an expert is someone who reliably gets the right result.'",
    difficulty: 0.1,
    sirs: 1,
    options: [
      { text: "Accumulated correct answers; reliably getting the right result", correct: true },
      { text: "A credential granted by a formal institution", errorType: "outside_knowledge_not_supported_by_passage", why: "Institutional credentialing is not the definition the passage discusses." },
      { text: "The ability to explain a topic simply to non-experts", errorType: "outside_knowledge_not_supported_by_passage", why: "Communication skill is not part of either definition the passage presents." },
      { text: "Years of experience in a field, regardless of outcomes", errorType: "outside_knowledge_not_supported_by_passage", why: "Years of experience alone is not the definition the passage attributes to the common view." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_expertise",
    stem: "The passage argues the outcome-based definition of expertise 'works poorly' for fields where:",
    reasoning: "The passage specifies this definition struggles 'for fields where the right result is only knowable long after the fact, or not at all,' using the example of a policy expert's advice.",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "The right result is only knowable long after the fact, or not at all", correct: true },
      { text: "There is only one universally agreed-upon expert", errorType: "outside_knowledge_not_supported_by_passage", why: "Not a condition the passage attaches to this definition's weakness." },
      { text: "Experts are paid extremely well for their advice", errorType: "outside_knowledge_not_supported_by_passage", why: "Compensation is irrelevant to the passage's critique of the outcome-based definition." },
      { text: "The field has no formal training programs", errorType: "outside_knowledge_not_supported_by_passage", why: "Formal training is not a factor the passage discusses in this critique." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_expertise",
    stem: "The passage identifies an advantage of the process-based definition of expertise as being:",
    reasoning: "The passage states this definition 'has the advantage of being assessable in the moment,' unlike the outcome-based definition, which may require waiting decades or longer.",
    difficulty: 0.4,
    sirs: 2,
    options: [
      { text: "It can be assessed in the moment, rather than requiring a long wait", correct: true },
      { text: "It guarantees the expert's predictions will be correct", correct: false, errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly separates good process from guaranteed correct outcomes ('whether or not that reasoning happens to produce a correct prediction')." },
      { text: "It requires no evidence at all to be evaluated", correct: false, errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage describes the process definition as reflecting 'a defensible weighing of the available evidence,' meaning evidence is still central." },
      { text: "It eliminates the need for any judgment about reasoning quality", correct: false, errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage explicitly raises the harder question of who judges whether the reasoning was defensible, meaning judgment is still required." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_expertise",
    stem: "The passage ends by raising a 'harder question' about who is qualified to judge whether a given process was defensible. Which scenario most directly illustrates this problem?",
    reasoning: "The passage's closing worry is a potential circularity: judging the quality of expert reasoning may itself require the same expertise being evaluated. A scenario where only insiders in a field can meaningfully assess another insider's reasoning directly illustrates this circularity concern.",
    difficulty: 0.6,
    sirs: 3,
    options: [
      { text: "Only economists are considered capable of judging whether another economist's policy reasoning was sound", correct: true },
      { text: "A policy's success is measured only decades after it was implemented", errorType: "true_statement_that_does_not_answer_the_question", why: "This illustrates the outcome-based definition's problem (delayed knowability), not the process-based definition's circularity problem being asked about." },
      { text: "An expert changes their prediction after new evidence emerges", errorType: "outside_knowledge_not_supported_by_passage", why: "Updating on new evidence is a normal, expected part of good reasoning, not an illustration of the judging-the-judges problem." },
      { text: "Two experts in the same field reach the same conclusion independently", errorType: "outside_knowledge_not_supported_by_passage", why: "Independent agreement doesn't raise the question of who is qualified to assess reasoning quality." },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_expertise",
    stem: "According to the passage, the process-based definition locates expertise in:",
    reasoning: "The passage states this alternative definition 'locates expertise not in outcomes but in process: an expert is someone whose reasoning...reflects a defensible weighing of the available evidence.'",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "The reasoning process, not the outcome", correct: true },
      { text: "The number of academic degrees an expert holds", errorType: "outside_knowledge_not_supported_by_passage", why: "Academic credentials are not part of the process-based definition the passage describes." },
      { text: "Public popularity or name recognition", errorType: "outside_knowledge_not_supported_by_passage", why: "Popularity is never discussed as a component of expertise in the passage." },
      { text: "Whether the outcome, once known, turns out correct", errorType: "passage_detail_misread_or_over_extrapolated", why: "This describes the outcome-based definition, which the process-based definition is explicitly contrasted against." },
    ],
  },

  // --- cars_silence_in_music (5) ---
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_silence_in_music",
    stem: "According to the passage, a rest in a musical score is sometimes mistakenly treated as:",
    reasoning: "The passage opens by stating a rest 'is sometimes treated as an absence, a gap between the notes that actually matter' — the view the passage goes on to argue against.",
    difficulty: 0.1,
    sirs: 1,
    options: [
      { text: "An absence, a gap between the notes that actually matter", correct: true },
      { text: "The most important element of any composition", errorType: "passage_detail_misread_or_over_extrapolated", why: "This overstates the passage's actual argument, which treats silence as meaningful but not necessarily 'the most important element.'" },
      { text: "A mistake made only by beginning composers", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage doesn't attribute this misconception specifically to beginners." },
      { text: "A recent addition to musical notation", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage makes no historical claim about when rests were introduced into notation." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_silence_in_music",
    stem: "The passage argues that composers who use silence deliberately understand a rest as:",
    reasoning: "The passage states such composers understand a rest as 'a specific compositional choice, shaping the listener's expectation of what comes next and controlling the emotional weight of the sound that follows it.'",
    difficulty: 0.3,
    sirs: 2,
    options: [
      { text: "A specific compositional choice shaping expectation and emotional weight", correct: true },
      { text: "An unavoidable technical limitation of musical notation", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage frames the rest as a deliberate choice, not a limitation being worked around." },
      { text: "A signal that the performer should stop playing entirely", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage discusses a rest's compositional function within a piece, not an instruction to end the performance." },
      { text: "A mistake in the composition that should be revised out", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage treats deliberate rests as valuable compositional tools, not errors to remove." },
    ],
  },
  {
    concept: "cars_reasoning_within_text",
    type: "passage",
    passage: "cars_silence_in_music",
    stem: "The passage states that the difference between a phrase that 'ends' and one that is 'interrupted' comes down to:",
    reasoning: "The passage directly states this difference 'often comes down entirely to the length and placement of the silence around it.'",
    difficulty: 0.3,
    sirs: 1,
    options: [
      { text: "The length and placement of the surrounding silence", correct: true },
      { text: "The specific instrument playing the phrase", errorType: "outside_knowledge_not_supported_by_passage", why: "Instrumentation is never discussed as the relevant factor in this distinction." },
      { text: "The overall tempo of the piece", errorType: "outside_knowledge_not_supported_by_passage", why: "Tempo is not identified as the deciding factor in the passage." },
      { text: "Whether the piece is played live or recorded", errorType: "outside_knowledge_not_supported_by_passage", why: "Live versus recorded performance is not discussed in the passage at all." },
    ],
  },
  {
    concept: "cars_reasoning_beyond_text",
    type: "passage",
    passage: "cars_silence_in_music",
    stem: "The passage compares hearing a rest as merely an absence of notes to reading punctuation as merely an absence of letters. This analogy is used to argue that:",
    reasoning: "The passage uses this analogy to argue that, just as punctuation actively structures meaning despite containing no letters, a musical rest actively does 'constructive work' despite containing no notes — the analogy's purpose is to make the constructive-function claim more intuitive.",
    difficulty: 0.5,
    sirs: 3,
    options: [
      { text: "Silence, like punctuation, does active constructive work despite seeming like a mere absence", correct: true },
      { text: "Music and language are fundamentally the same kind of system", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage draws a narrow structural analogy about absence-as-function, not a broad claim that music and language are the same kind of system." },
      { text: "Rests should be notated using punctuation marks instead of musical symbols", errorType: "outside_knowledge_not_supported_by_passage", why: "The passage makes no proposal about notation systems; it's drawing a conceptual, not a notational, analogy." },
      { text: "Punctuation is more important to meaning than the words themselves", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage doesn't rank punctuation above words in importance; it uses punctuation to illustrate a general point about functional 'gaps.'" },
    ],
  },
  {
    concept: "cars_comprehension",
    type: "passage",
    passage: "cars_silence_in_music",
    stem: "According to the passage, a well-placed rest shapes:",
    reasoning: "The passage states a well-placed rest is 'shaping the listener's expectation of what comes next and controlling the emotional weight of the sound that follows it' — both expectation and emotional weight.",
    difficulty: 0.2,
    sirs: 1,
    options: [
      { text: "The listener's expectation and the emotional weight of what follows", correct: true },
      { text: "Only the total runtime of the piece", errorType: "passage_detail_misread_or_over_extrapolated", why: "The passage's focus is on the rest's perceptual and emotional effect, not simply on timing/runtime." },
      { text: "Only the technical difficulty of the performance", errorType: "outside_knowledge_not_supported_by_passage", why: "Performance difficulty is not discussed in the passage." },
      { text: "The key signature of the piece", errorType: "outside_knowledge_not_supported_by_passage", why: "Key signature is a separate musical concept not addressed in the passage." },
    ],
  },
];
